In [1]:
import random

import numpy as np
import matplotlib.pyplot as plt
from rich.jupyter import display

In [1]:
np.random.rand((10))

In [2]:
plt.plot(np.random.rand(10))

In [3]:
import pandas as pd

In [4]:
import ollama

  0%|          | 0/10 [00:00<?, ?it/s]

ConnectError: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение

In [11]:
from tqdm import notebook

In [14]:
sentences = []
for i in notebook.tqdm(range(10)):
    resp = ollama.generate(
        'gemma2:9b-instruct-q4_0',
        'Generate sentence in styles of greate writers which have 10-15 word. Return only sentence without additional information.',
    )['response']
    sentences.append(resp)

  0%|          | 0/100 [00:00<?, ?it/s]

KeyboardInterrupt:

In [16]:
sentences = []
for i in notebook.tqdm(range(10)):
    resp = ollama.generate(
        'gemma2:9b-instruct-q4_0',
        'Write story. Each sentence must have 10-15 word.',
    )['response']
    sentences.extend(resp.split('.'))

  0%|          | 0/10 [00:00<?, ?it/s]

In [17]:
prompt = '''Generate 20 unique sentences that meet these requirements:

1. Length constraints:
   - Each sentence should be between 5-15 words
   - Vary sentence lengths naturally within this range

2. Structural diversity:
   - Mix simple, compound, and complex sentences
   - Use different sentence openings (subject, prepositional phrase, gerund, etc.)
   - Vary between declarative, interrogative, and exclamatory sentences
   - Include both active and passive voice constructions

3. Vocabulary requirements:
   - Use precise, specific verbs instead of generic ones (e.g., "sprint" vs "run")
   - Include descriptive adjectives and adverbs without overuse
   - Avoid repeating words across sentences except for essential articles and prepositions
   - Draw vocabulary from different domains (nature, technology, daily life, etc.)

4. Semantic constraints:
   - Each sentence should be logically coherent and self-contained
   - Include both concrete and abstract concepts
   - Vary emotional tone (neutral, positive, negative)
   - Mix formal and informal register

5. Format output as:
   - One sentence per line
   - Number each sentence
   - Include a brief tag indicating primary structure type [Simple/Compound/Complex]

# Example Output Format:

1. [Simple] The old maple tree erupted in autumn colors.
2. [Complex] While thunder rolled across the valley, migrating geese soared southward.
3. [Compound] The quarterback fumbled the ball, but his teammate recovered it swiftly.

# Additional Parameters:
- Domain focus: Team Sports
- Tone emphasis: formal
'''

In [18]:
tones = ['formal', 'informal']
domains = '''
# Academic & Scientific Domains

1. Biology & Life Sciences
   - Example: "The mitochondria efficiently converted glucose into cellular energy."
   - Subtopics: genetics, ecology, anatomy, evolution

2. Physics & Astronomy
   - Example: "Neutron stars collapse under their intense gravitational force."
   - Subtopics: quantum mechanics, cosmology, thermodynamics

3. Chemistry
   - Example: "The catalyst accelerated the reaction without being consumed."
   - Subtopics: organic chemistry, materials science, biochemistry

# Professional & Technical Domains

4. Business & Finance
   - Example: "The merger created substantial synergies for both companies."
   - Subtopics: marketing, accounting, investments, management

5. Technology & Computing
   - Example: "The algorithm efficiently sorted through millions of data points."
   - Subtopics: programming, cybersecurity, artificial intelligence

6. Engineering
   - Example: "The bridge's suspension cables distributed weight evenly."
   - Subtopics: mechanical, electrical, civil, aerospace

# Everyday Life Domains

7. Daily Activities
   - Example: "She quickly prepared breakfast while checking her emails."
   - Subtopics: routines, chores, work life, leisure

8. Social Interactions
   - Example: "The neighbors gathered for their annual block party."
   - Subtopics: relationships, communication, events

9. Home & Living
   - Example: "Sunlight streamed through the newly installed skylight."
   - Subtopics: decoration, maintenance, gardening

# Arts & Culture Domains

10. Literature & Writing
    - Example: "The author crafted intricate metaphors throughout the novel."
    - Subtopics: poetry, journalism, creative writing

11. Visual Arts
    - Example: "The sculptor chiseled delicate features into the marble."
    - Subtopics: painting, photography, design

12. Performing Arts
    - Example: "The dancer executed a perfect pirouette on stage."
    - Subtopics: music, theater, dance

# Nature & Environment

13. Weather & Climate
    - Example: "Storm clouds gathered ominously on the horizon."
    - Subtopics: meteorology, seasons, natural phenomena

14. Geography & Landscapes
    - Example: "The canyon walls revealed millennia of geological history."
    - Subtopics: landforms, ecosystems, urban geography

15. Wildlife & Animals
    - Example: "The arctic fox's coat changed color with the seasons."
    - Subtopics: behavior, habitats, adaptation

# Sports & Recreation

16. Team Sports
    - Example: "The quarterback threw a perfect spiral to the receiver."
    - Subtopics: strategy, competition, training

17. Individual Sports
    - Example: "The gymnast maintained perfect balance on the beam."
    - Subtopics: techniques, equipment, performance

# Historical & Cultural

18. Historical Events
    - Example: "Ancient civilizations developed sophisticated irrigation systems."
    - Subtopics: wars, discoveries, social movements

19. Cultural Practices
    - Example: "Traditional artisans passed down their techniques through generations."
    - Subtopics: customs, traditions, celebrations

# Emotional & Psychological

20. Emotions & Feelings
    - Example: "Anticipation built as she opened the mysterious package."
    - Subtopics: moods, reactions, relationships
'''
_domains = []
for line in domains.split('\n'):
    if line.strip() and not (line.startswith(' ') or line.startswith('#')):
        _domains.append(line.split('.')[1].strip())

_domains

Generated 1500 valid combinations

Prompt 1:
Generate 11 unique sentences that meet these requirements:

1. Length constraints:
   - Sentence length: 6-15 words
   - Maximum word repetition: 2 times
   - Technical term density: medium

2. Structural diversity:
   - Mix simple, compound, and complex sentences
   - Use different sentence openings (subject, prepositional phrase, gerund, etc.)
   - Vary between declarative, interrogative, and exclamatory sentences
   - Include both active and passive voice constructions

3. Vocabulary requirements:
   - Use precise, specific verbs instead of generic ones (e.g., "sprint" vs "run")
   - Include descriptive adjectives and adverbs without overuse
   - Avoid repeating words across sentences except for essential articles and prepositions
   - Draw vocabulary from different domains (nature, technology, daily life, etc.)

4. Semantic constraints:
   - Each sentence should be logically coherent and self-contained
   - Include both concrete and abstract concepts
   - Vary emotional tone (neutral, positive, negative)
   - Mix formal and informal register

5. Format output as:
   - One sentence per line
   - Number each sentence
   - Include a brief tag indicating primary structure type [Simple/Compound/Complex]
   - Return only sentences without additional information.

# Additional Parameters:
   Domain:
      - Category: professional
      - Focus areas: business, finance, law

   Vocabulary:
      - Register: informal
      - Specificity: mixed
      - Required elements per sentence:
        * Dynamic verbs: 3
        * Sensory adjectives: 2
        * Abstract nouns: 1
        * Concrete nouns: 2

   Structure:
      - Sentence type distribution:
        * Simple: 30%
        * Compound: 50%
        * Complex: 20%
      - Preferred opener: participial
      - Special structure: cumulative

# Example Output Format:

1. [Simple] The old maple tree erupted in autumn colors.
2. [Complex] While thunder rolled across the valley, migrating geese soared southward.
3. [Compound] The quarterback fumbled the ball, but his teammate recovered it swiftly.

--------------------------------------------------------------------------------

Prompt 2:
Generate 11 unique sentences that meet these requirements:

1. Length constraints:
   - Sentence length: 6-15 words
   - Maximum word repetition: 2 times
   - Technical term density: low

2. Structural diversity:
   - Mix simple, compound, and complex sentences
   - Use different sentence openings (subject, prepositional phrase, gerund, etc.)
   - Vary between declarative, interrogative, and exclamatory sentences
   - Include both active and passive voice constructions

3. Vocabulary requirements:
   - Use precise, specific verbs instead of generic ones (e.g., "sprint" vs "run")
   - Include descriptive adjectives and adverbs without overuse
   - Avoid repeating words across sentences except for essential articles and prepositions
   - Draw vocabulary from different domains (nature, technology, daily life, etc.)

4. Semantic constraints:
   - Each sentence should be logically coherent and self-contained
   - Include both concrete and abstract concepts
   - Vary emotional tone (neutral, positive, negative)
   - Mix formal and informal register

5. Format output as:
   - One sentence per line
   - Number each sentence
   - Include a brief tag indicating primary structure type [Simple/Compound/Complex]
   - Return only sentences without additional information.

# Additional Parameters:
   Domain:
      - Category: arts
      - Focus areas: literature, visual_arts, music

   Vocabulary:
      - Register: mixed
      - Specificity: general
      - Required elements per sentence:
        * Dynamic verbs: 3
        * Sensory adjectives: 2
        * Abstract nouns: 1
        * Concrete nouns: 2

   Structure:
      - Sentence type distribution:
        * Simple: 30%
        * Compound: 40%
        * Complex: 30%
      - Preferred opener: subject
      - Special structure: balanced

# Example Output Format:

1. [Simple] The old maple tree erupted in autumn colors.
2. [Complex] While thunder rolled across the valley, migrating geese soared southward.
3. [Compound] The quarterback fumbled the ball, but his teammate recovered it swiftly.

--------------------------------------------------------------------------------

Prompt 3:
Generate 11 unique sentences that meet these requirements:

1. Length constraints:
   - Sentence length: 6-15 words
   - Maximum word repetition: 2 times
   - Technical term density: low

2. Structural diversity:
   - Mix simple, compound, and complex sentences
   - Use different sentence openings (subject, prepositional phrase, gerund, etc.)
   - Vary between declarative, interrogative, and exclamatory sentences
   - Include both active and passive voice constructions

3. Vocabulary requirements:
   - Use precise, specific verbs instead of generic ones (e.g., "sprint" vs "run")
   - Include descriptive adjectives and adverbs without overuse
   - Avoid repeating words across sentences except for essential articles and prepositions
   - Draw vocabulary from different domains (nature, technology, daily life, etc.)

4. Semantic constraints:
   - Each sentence should be logically coherent and self-contained
   - Include both concrete and abstract concepts
   - Vary emotional tone (neutral, positive, negative)
   - Mix formal and informal register

5. Format output as:
   - One sentence per line
   - Number each sentence
   - Include a brief tag indicating primary structure type [Simple/Compound/Complex]
   - Return only sentences without additional information.

# Additional Parameters:
   Domain:
      - Category: natural
      - Focus areas: ecology, weather, geography

   Vocabulary:
      - Register: formal
      - Specificity: technical
      - Required elements per sentence:
        * Dynamic verbs: 3
        * Sensory adjectives: 2
        * Abstract nouns: 1
        * Concrete nouns: 2

   Structure:
      - Sentence type distribution:
        * Simple: 40%
        * Compound: 30%
        * Complex: 30%
      - Preferred opener: prepositional
      - Special structure: periodic

# Example Output Format:

1. [Simple] The old maple tree erupted in autumn colors.
2. [Complex] While thunder rolled across the valley, migrating geese soared southward.
3. [Compound] The quarterback fumbled the ball, but his teammate recovered it swiftly.

--------------------------------------------------------------------------------

In [19]:
from itertools import product
from typing import Dict, List, Tuple
import random
import json

class PromptCombinator:
    def __init__(self):
        # Define the parameter options
        self.parameters = {
            "domains": {
                "academic": ["biology", "physics", "chemistry"],
                "technical": ["computer_science", "engineering", "mathematics"],
                "natural": ["ecology", "weather", "geography"],
                "professional": ["business", "finance", "law"],
                "arts": ["literature", "visual_arts", "music"]
            },

            "vocabulary_requirements": {
                "parts_of_speech": {
                    "dynamic_verbs": [2, 3, 4],
                    "sensory_adjectives": [1, 2, 3],
                    "abstract_nouns": [1, 2],
                    "concrete_nouns": [2, 3, 4]
                },
                "register": ["formal", "informal", "mixed"],
                "specificity": ["technical", "general", "mixed"]
            },

            "structural_patterns": {
                "sentence_types": {
                    "simple": [20, 30, 40],  # percentage
                    "compound": [30, 40, 50],
                    "complex": [20, 30, 40]
                },
                "openers": ["adverbial", "participial", "prepositional", "subject"],
                "special_structures": ["periodic", "cumulative", "balanced", "parallel"]
            },

            "constraints": {
                "sentence_length": {
                    "min": [5, 6, 7],
                    "max": [12, 15, 18]
                },
                "word_repetition": [1, 2, 3],  # max times a word can be repeated
                "technical_density": ["low", "medium", "high"]  # percentage of technical terms
            }
        }

    def validate_sentence_distribution(self, simple: int, compound: int, complex: int) -> bool:
        """Check if sentence type percentages sum to 100"""
        return simple + compound + complex == 100

    def generate_combinations(self, max_combinations: int = 1000) -> List[Dict]:
        """Generate valid combinations of parameters"""
        # Create lists of items to combine
        domain_categories = list(self.parameters["domains"].keys())
        registers = self.parameters["vocabulary_requirements"]["register"]
        specificities = self.parameters["vocabulary_requirements"]["specificity"]
        openers = self.parameters["structural_patterns"]["openers"]
        special_structures = self.parameters["structural_patterns"]["special_structures"]
        technical_densities = self.parameters["constraints"]["technical_density"]

        # Generate combinations
        combinations = list(product(
            domain_categories,
            registers,
            specificities,
            openers,
            special_structures,
            technical_densities
        ))

        # Convert combinations to structured prompts
        prompts = []
        for combo in combinations:
            domain_cat, register, specificity, opener, special_structure, tech_density = combo

            # Only include valid sentence type distributions
            for simple in self.parameters["structural_patterns"]["sentence_types"]["simple"]:
                for compound in self.parameters["structural_patterns"]["sentence_types"]["compound"]:
                    for complex in self.parameters["structural_patterns"]["sentence_types"]["complex"]:
                        if self.validate_sentence_distribution(simple, compound, complex):
                            prompt = {
                                "domain": {
                                    "category": domain_cat,
                                    "specific_domains": self.parameters["domains"][domain_cat]
                                },
                                "vocabulary": {
                                    "register": register,
                                    "specificity": specificity,
                                    "requirements": {
                                        "dynamic_verbs": 3,  # Default values
                                        "sensory_adjectives": 2,
                                        "abstract_nouns": 1,
                                        "concrete_nouns": 2
                                    }
                                },
                                "structure": {
                                    "distribution": {
                                        "simple": simple,
                                        "compound": compound,
                                        "complex": complex
                                    },
                                    "preferred_opener": opener,
                                    "special_structure": special_structure
                                },
                                "constraints": {
                                    "sentence_length": {
                                        "min": 6,
                                        "max": 15
                                    },
                                    "word_repetition": 2,
                                    "technical_density": tech_density
                                }
                            }
                            prompts.append(prompt)

        return random.choices(prompts, k=max_combinations)

    def generate_prompt_text(self, params: Dict) -> str:
        """Convert parameter combination into actual prompt text"""
        prompt = f"""Generate 5 unique sentences that meet these requirements:

1. Length constraints:
   - Sentence length: {params['constraints']['sentence_length']['min']}-{params['constraints']['sentence_length']['max']} words
   - Maximum word repetition: {params['constraints']['word_repetition']} times
   - Technical term density: {params['constraints']['technical_density']}

2. Structural diversity:
   - Mix simple, compound, and complex sentences
   - Use different sentence openings (subject, prepositional phrase, gerund, etc.)
   - Vary between declarative, interrogative, and exclamatory sentences
   - Include both active and passive voice constructions

3. Vocabulary requirements:
   - Use precise, specific verbs instead of generic ones (e.g., "sprint" vs "run")
   - Include descriptive adjectives and adverbs without overuse
   - Avoid repeating words across sentences except for essential articles and prepositions
   - Draw vocabulary from different domains (nature, technology, daily life, etc.)

4. Semantic constraints:
   - Each sentence should be logically coherent and self-contained
   - Include both concrete and abstract concepts
   - Vary emotional tone (neutral, positive, negative)
   - Mix formal and informal register

5. Format output as:
   - One sentence per line
   - Number each sentence
   - Include a brief tag indicating primary structure type [Simple/Compound/Complex]
   - Return only sentences without additional information.

# Additional Parameters:
   Domain:
      - Category: {params['domain']['category']}
      - Focus areas: {', '.join(params['domain']['specific_domains'])}

   Vocabulary:
      - Register: {params['vocabulary']['register']}
      - Specificity: {params['vocabulary']['specificity']}
      - Required elements per sentence:
        * Dynamic verbs: {params['vocabulary']['requirements']['dynamic_verbs']}
        * Sensory adjectives: {params['vocabulary']['requirements']['sensory_adjectives']}
        * Abstract nouns: {params['vocabulary']['requirements']['abstract_nouns']}
        * Concrete nouns: {params['vocabulary']['requirements']['concrete_nouns']}

   Structure:
      - Sentence type distribution:
        * Simple: {params['structure']['distribution']['simple']}%
        * Compound: {params['structure']['distribution']['compound']}%
        * Complex: {params['structure']['distribution']['complex']}%
      - Preferred opener: {params['structure']['preferred_opener']}
      - Special structure: {params['structure']['special_structure']}

# Example Output Format:

1. [Simple] The old maple tree erupted in autumn colors.
2. [Complex] While thunder rolled across the valley, migrating geese soared southward.
3. [Compound] The quarterback fumbled the ball, but his teammate recovered it swiftly.
"""
        return prompt

  0%|          | 0/1500 [00:00<?, ?it/s]

In [9]:
combinator = PromptCombinator()

# Generate combinations
combinations = combinator.generate_combinations(max_combinations=100)

# Generate some example prompts
print(f"Generated {len(combinations)} valid combinations")

# Print a few example prompts
prompts = []
for i, combo in enumerate(combinations[:3]):
    print(f"\nPrompt {i+1}:")
    print(combinator.generate_prompt_text(combo))
    print("-" * 80)
    prompts.append(combinator.generate_prompt_text(combo))

  0%|          | 0/100 [00:00<?, ?it/s]

In [20]:
sentences_llama = []
for i, combo in notebook.tqdm(enumerate(combinations), total=len(combinations)):
    prompt = combinator.generate_prompt_text(combo)
    resp = ollama.generate(
        'llama3.2',
        prompt,
    )['response']
    sentences_llama.append(resp)

In [10]:
sentences_gemma = []
for i, combo in notebook.tqdm(enumerate(combinations), total=len(combinations)):
    prompt = combinator.generate_prompt_text(combo)
    resp = ollama.generate(
        'gemma2:2b',
        prompt,
    )['response']
    sentences_gemma.append(resp)

In [21]:
def split_sentence(sentence):
    sentence = sentence.split('\n\n')
    if len(sentence) > 1:
        return sentence[1]
    
    return sentence[0]


def format_sentences(sentences):
    sentences = [split_sentence(sentence) for sentence in sentences]
    sentences = [sentence.split('\n') for sentence in sentences]
    sentences = sum(sentences, [])
    sentences = pd.Series(sentences)
    sentences = sentences[sentences.apply(lambda x: '[' in x and ']' in x)]
    sentences = sentences.apply(lambda x: x.split(']')[1].strip())
    return sentences

NameError: name 'sentences_gemma' is not defined

In [12]:
sentences_llama

NameError: name 'sentences_gemma' is not defined

In [22]:
sentences_llama_s = format_sentences(sentences_llama)
sentences_gemma_s = format_sentences(sentences_gemma)

0        After analyzing market trends, our financial t...
1        The CEO's presentation focused on innovative s...
2        As the sales figures revealed, the marketing s...
3        What a relief it felt when we finally closed t...
4        The company's commitment to corporate social r...
                               ...
15496    The marketing strategy involved a multi-channe...
15497    As negotiations between the parties drew to a ...
15498    The company's new policy aimed to reduce carbo...
15499    Through a combination of rigorous testing and ...
15500    The innovative technology utilized advanced ma...
Length: 15475, dtype: object

In [13]:
sentences_gemma

0      The painter's bold brushstrokes danced across ...
1      As she wandered through the gallery, the poet'...
2      With each note, the musician's fingers weaved ...
3      The scent of fresh paint wafted from the open ...
4      Through the city streets, the sound system rev...
                             ...
463    Flickering LED lights illuminated the dark roo...
464    As engineers designed a new algorithm, they di...
465    The researchers conducted extensive tests, obt...
466    With her quick reflexes, the firefighter avoid...
467    In a surprising twist, the company's CEO annou...
Length: 464, dtype: object

In [94]:
sentences_llama_s

0      As morning sunbeams pierced the forest canopy,...
1      The stormy weather brought heavy rainfall and ...
2      In contrast to yesterday's calmness, today's f...
3      Oh, what a breathtaking sight the aurora borea...
4      The vast expanse of the Grand Canyon revealed ...
                             ...
471    As electrons oscillated around the nucleus, qu...
472    Oxygen levels in freshwater sources are crucia...
473    The researcher carefully analyzed data using s...
474    When photons collided with atomic nuclei, incr...
475    Through recursive processes of mitosis and mei...
Length: 466, dtype: object

In [26]:
sentences_gemma_s

In [25]:
sentences_gemma_s.name = 'gemma2-2b-prompt'
sentences_llama_s.name = 'llama3.2-3b-prompt'

sentences_gemma_s.to_frame().to_csv('../data/dpo_texts_samples/gemma.csv')
sentences_llama_s.to_frame().to_csv('../data/dpo_texts_samples/llama.csv')

15408

In [99]:
pd.concat([sentences_llama_s, sentences_gemma_s],axis=1)

,llama3.2-3b-prompt,gemma2-2b-prompt
0,"As morning sunbeams pierced the forest canopy,...",Verdant leaves burst into vibrant hues as fall...
1,The stormy weather brought heavy rainfall and ...,The wind whips through tall grasses as moistur...
2,"In contrast to yesterday's calmness, today's f...",The biologist's meticulously observed the migr...
3,"Oh, what a breathtaking sight the aurora borea...",A symphony of chirps echoed through the dense ...
4,The vast expanse of the Grand Canyon revealed ...,"The monsoon brought forth a torrent of rain, i..."
...,...,...
511,NaN,Proton decay could offer insights into fundame...
512,NaN,The electron cloud's intricate pattern reveals...
513,NaN,Observing the cellular structure revealed the ...
514,NaN,A sudden gust of wind carried pollen from one ...
515,NaN,The experimental data indicated an anomalous i...

In [52]:
sentences = [sentence.split('\n\n')[1] for sentence in sentences]

In [54]:
sentences = [sentence.split('\n') for sentence in sentences]
sentences = sum(sentences, [])

In [55]:
pd.Series(sentences)

0       1. [Simple] The biologist carefully measured t...
1       2. [Complex] As the solar eclipse approached, ...
2       3. [Compound] With each step, the hikers climb...
3       4. [Exclamatory] What an incredible feat of en...
4       5. [Simple] The physicist hypothesized a new t...
                              ...
1357    16. [Interrogative] Does the new material exhi...
1358    17. [Simple] The ocean's surface temperature f...
1359    18. [Complex] Through advanced statistical ana...
1360    19. [Compound] The biodegradable polymer showe...
1361    20. [Exclamatory] The groundbreaking discovery...
Length: 1362, dtype: object

In [24]:
sentences = [sentence.split('\n') for sentence in sentences]
sentences = sum(sentences, [])

In [56]:
sentences = pd.Series(sentences)
sentences = sentences[sentences.apply(lambda x: '[' in x and ']' in x)]
sentences

0       1. [Simple] The biologist carefully measured t...
1       2. [Complex] As the solar eclipse approached, ...
2       3. [Compound] With each step, the hikers climb...
3       4. [Exclamatory] What an incredible feat of en...
4       5. [Simple] The physicist hypothesized a new t...
                              ...
1357    16. [Interrogative] Does the new material exhi...
1358    17. [Simple] The ocean's surface temperature f...
1359    18. [Complex] Through advanced statistical ana...
1360    19. [Compound] The biodegradable polymer showe...
1361    20. [Exclamatory] The groundbreaking discovery...
Length: 1362, dtype: object

In [57]:
sentences = sentences.apply(lambda x: x.split(']')[1].strip())
sentences

0       The biologist carefully measured the diameter ...
1       As the solar eclipse approached, physicists ca...
2       With each step, the hikers climbed higher into...
3       What an incredible feat of engineering that sk...
4       The physicist hypothesized a new theory to exp...
                              ...
1357    Does the new material exhibit improved thermal...
1358    The ocean's surface temperature fluctuated wit...
1359    Through advanced statistical analysis, researc...
1360    The biodegradable polymer showed remarkable re...
1361    The groundbreaking discovery revolutionized ou...
Length: 1362, dtype: object

In [1]:
import pandas as pd

In [5]:
metadata = pd.read_parquet('../data/dpo_dataset/samples_data.parquet')
metadata

,gen_id,audio_id,speaker_id,text,gpt_codes
0,0,dd116c13-a4ca-11ef-a829-346f24a52a12.wav,constance-035,"As morning sunbeams pierced the forest canopy,...","[54, 85, 492, 983, 442, 105, 40, 280, 243, 115..."
1,1,de61bef4-a4ca-11ef-adc2-346f24a52a12.wav,constance-035,"As morning sunbeams pierced the forest canopy,...","[76, 40, 584, 474, 527, 115, 728, 640, 534, 22..."
2,2,dfaeebc0-a4ca-11ef-9a51-346f24a52a12.wav,constance-035,"As morning sunbeams pierced the forest canopy,...","[640, 487, 28, 280, 294, 8, 22, 571, 76, 627, ..."
3,3,e1077360-a4ca-11ef-95da-346f24a52a12.wav,constance-035,"As morning sunbeams pierced the forest canopy,...","[76, 225, 28, 231, 689, 8, 258, 640, 13, 627, ..."
4,4,e2706d5a-a4ca-11ef-aa75-346f24a52a12.wav,constance-035,"As morning sunbeams pierced the forest canopy,...","[54, 437, 755, 130, 948, 76, 487, 40, 436, 243..."
...,...,...,...,...,...
245,0,46e9dcc7-a4cc-11ef-a2f1-346f24a52a12.wav,vincent-001,"Meanwhile, across town, experts debated the im...","[808, 2, 350, 65, 37, 257, 30, 342, 713, 842, ..."
246,1,492fe4f0-a4cc-11ef-9894-346f24a52a12.wav,vincent-001,"Meanwhile, across town, experts debated the im...","[15, 668, 199, 269, 2, 257, 263, 9, 706, 673, ..."
247,2,4aa98f55-a4cc-11ef-ba33-346f24a52a12.wav,vincent-001,"Meanwhile, across town, experts debated the im...","[551, 2, 269, 199, 129, 275, 342, 611, 795, 84..."
248,3,4c1533f8-a4cc-11ef-a26e-346f24a52a12.wav,vincent-001,"Meanwhile, across town, experts debated the im...","[15, 668, 199, 269, 202, 257, 820, 207, 67, 49..."
249,4,4d8e669d-a4cc-11ef-baf7-346f24a52a12.wav,vincent-001,"Meanwhile, across town, experts debated the im...","[412, 37, 416, 66, 2, 753, 69, 611, 114, 842, ..."

In [9]:
samples = metadata.groupby(['speaker_id', 'text']).sample(2, random_state=42)
samples

,gen_id,audio_id,speaker_id,text,gpt_codes
6,1,e4f364e1-a4ca-11ef-b0f6-346f24a52a12.wav,LJ001-0001,"As morning sunbeams pierced the forest canopy,...","[85, 59, 256, 280, 630, 243, 258, 640, 76, 365..."
9,4,e8cd4603-a4ca-11ef-a789-346f24a52a12.wav,LJ001-0001,"As morning sunbeams pierced the forest canopy,...","[442, 323, 81, 186, 527, 391, 258, 76, 487, 29..."
133,3,92b49ff6-a4cb-11ef-83b7-346f24a52a12.wav,LJ001-0001,"As negotiations concluded, key stakeholders ca...","[442, 323, 68, 635, 186, 422, 266, 701, 767, 3..."
131,1,901cf6a8-a4cb-11ef-9b0f-346f24a52a12.wav,LJ001-0001,"As negotiations concluded, key stakeholders ca...","[76, 59, 655, 68, 280, 527, 405, 155, 369, 767..."
56,1,227f7427-a4cb-11ef-b78f-346f24a52a12.wav,LJ001-0001,"In contrast to yesterday's calmness, today's f...","[551, 99, 640, 70, 225, 571, 487, 74, 59, 294,..."
...,...,...,...,...,...
47,2,16d27dd1-a4cb-11ef-ba05-346f24a52a12.wav,vincent-001,The stormy weather brought heavy rainfall and ...,"[905, 37, 454, 622, 346, 273, 53, 323, 440, 26..."
121,1,8213df7f-a4cb-11ef-95e9-346f24a52a12.wav,vincent-001,The vast expanse of the Grand Canyon revealed ...,"[168, 126, 37, 192, 375, 389, 158, 323, 692, 4..."
122,2,833abc91-a4cb-11ef-bf84-346f24a52a12.wav,vincent-001,The vast expanse of the Grand Canyon revealed ...,"[815, 37, 471, 414, 167, 725, 389, 323, 53, 43..."
195,0,e0daf1d0-a4cb-11ef-9199-346f24a52a12.wav,vincent-001,Under close supervision from investors and aud...,"[494, 619, 11, 127, 62, 429, 651, 434, 8, 266,..."
198,3,e5a3b571-a4cb-11ef-9da1-346f24a52a12.wav,vincent-001,Under close supervision from investors and aud...,"[551, 56, 210, 403, 37, 753, 640, 618, 820, 26..."

In [11]:
mel_cond_w = samples.groupby(['speaker_id', 'text']).nth(0)
mel_cond_w

                                                                 gen_id  \
speaker_id    text
LJ001-0001    As morning sunbeams pierced the forest canopy, ...      1
              As negotiations concluded, key stakeholders cap...      3
              In contrast to yesterday's calmness, today's fo...      1
              Innovative software applications have transform...      0
              Meanwhile, across town, experts debated the imp...      0
              Oh, what a breathtaking sight the aurora boreal...      4
              The finance minister disclosed the budget cuts ...      2
              The stormy weather brought heavy rainfall and s...      1
              The vast expanse of the Grand Canyon revealed h...      0
              Under close supervision from investors and audi...      0
constance-035 As morning sunbeams pierced the forest canopy, ...      0
              As negotiations concluded, key stakeholders cap...      1
              In contrast to yesterday's calmness, today's fo...      3
              Innovative software applications have transform...      4
              Meanwhile, across town, experts debated the imp...      2
              Oh, what a breathtaking sight the aurora boreal...      0
              The finance minister disclosed the budget cuts ...      1
              The stormy weather brought heavy rainfall and s...      4
              The vast expanse of the Grand Canyon revealed h...      0
              Under close supervision from investors and audi...      2
samantha-008  As morning sunbeams pierced the forest canopy, ...      0
              As negotiations concluded, key stakeholders cap...      0
              In contrast to yesterday's calmness, today's fo...      4
              Innovative software applications have transform...      2
              Meanwhile, across town, experts debated the imp...      2
              Oh, what a breathtaking sight the aurora boreal...      1
              The finance minister disclosed the budget cuts ...      1
              The stormy weather brought heavy rainfall and s...      3
              The vast expanse of the Grand Canyon revealed h...      1
              Under close supervision from investors and audi...      1
spencer-015   As morning sunbeams pierced the forest canopy, ...      3
              As negotiations concluded, key stakeholders cap...      4
              In contrast to yesterday's calmness, today's fo...      2
              Innovative software applications have transform...      3
              Meanwhile, across town, experts debated the imp...      1
              Oh, what a breathtaking sight the aurora boreal...      4
              The finance minister disclosed the budget cuts ...      1
              The stormy weather brought heavy rainfall and s...      3
              The vast expanse of the Grand Canyon revealed h...      2
              Under close supervision from investors and audi...      4
vincent-001   As morning sunbeams pierced the forest canopy, ...      1
              As negotiations concluded, key stakeholders cap...      1
              In contrast to yesterday's calmness, today's fo...      0
              Innovative software applications have transform...      3
              Meanwhile, across town, experts debated the imp...      0
              Oh, what a breathtaking sight the aurora boreal...      4
              The finance minister disclosed the budget cuts ...      4
              The stormy weather brought heavy rainfall and s...      1
              The vast expanse of the Grand Canyon revealed h...      1
              Under close supervision from investors and audi...      0

                                                                                                  audio_id  \
speaker_id    text
LJ001-0001    As morning sunbeams pierced the forest canopy, ...  e4f364e1-a4ca-11ef-b0f6-346f24a52a12.wav
              As negotiations concluded, key stakeholders cap...  92b49ff6-a4cb-11ef-83b7-346f24a52a12.wav
              In contrast to yesterday's calmness, today's fo...  227f7427-a4cb-11ef-b78f-346f24a52a12.wav
              Innovative software applications have transform...  efec9fcb-a4cb-11ef-8fb1-346f24a52a12.wav
              Meanwhile, across town, experts debated the imp...  267c2f6c-a4cc-11ef-8bb1-346f24a52a12.wav
              Oh, what a breathtaking sight the aurora boreal...  48dfbed8-a4cb-11ef-9ca7-346f24a52a12.wav
              The finance minister disclosed the budget cuts ...  b06cade4-a4cb-11ef-9df3-346f24a52a12.wav
              The stormy weather brought heavy rainfall and s...  05072a7e-a4cb-11ef-b2a0-346f24a52a12.wav
              The vast expanse of the Grand Canyon revealed h...  688b2755-a4cb-11ef-a9ec-346f24a52a12.wav
              Under close supervision from investors and audi...  cbaaf6b1-a4cb-11ef-a9c0-346f24a52a12.wav
constance-035 As morning sunbeams pierced the forest canopy, ...  dd116c13-a4ca-11ef-a829-346f24a52a12.wav
              As negotiations concluded, key stakeholders cap...  89377c5f-a4cb-11ef-8714-346f24a52a12.wav
              In contrast to yesterday's calmness, today's fo...  1e94b196-a4cb-11ef-84a0-346f24a52a12.wav
              Innovative software applications have transform...  eeb523d5-a4cb-11ef-8adb-346f24a52a12.wav
              Meanwhile, across town, experts debated the imp...  1a917e08-a4cc-11ef-bfe3-346f24a52a12.wav
              Oh, what a breathtaking sight the aurora boreal...  3dccddf6-a4cb-11ef-9dc1-346f24a52a12.wav
              The finance minister disclosed the budget cuts ...  aaa48b9e-a4cb-11ef-bc2f-346f24a52a12.wav
              The stormy weather brought heavy rainfall and s...  030f39c0-a4cb-11ef-8716-346f24a52a12.wav
              The vast expanse of the Grand Canyon revealed h...  6029f2de-a4cb-11ef-ad9d-346f24a52a12.wav
              Under close supervision from investors and audi...  c75a6817-a4cb-11ef-886c-346f24a52a12.wav
samantha-008  As morning sunbeams pierced the forest canopy, ...  ea1cf566-a4ca-11ef-b954-346f24a52a12.wav
              As negotiations concluded, key stakeholders cap...  95627b68-a4cb-11ef-a310-346f24a52a12.wav
              In contrast to yesterday's calmness, today's fo...  2e6ddc61-a4cb-11ef-a85c-346f24a52a12.wav
              Innovative software applications have transform...  f9e5e637-a4cb-11ef-8f88-346f24a52a12.wav
              Meanwhile, across town, experts debated the imp...  3a216622-a4cc-11ef-877f-346f24a52a12.wav
              Oh, what a breathtaking sight the aurora boreal...  4b8399c6-a4cb-11ef-95f0-346f24a52a12.wav
              The finance minister disclosed the budget cuts ...  b47017ed-a4cb-11ef-ad64-346f24a52a12.wav
              The stormy weather brought heavy rainfall and s...  0ce3d647-a4cb-11ef-b627-346f24a52a12.wav
              The vast expanse of the Grand Canyon revealed h...  71cb90ca-a4cb-11ef-95e7-346f24a52a12.wav
              Under close supervision from investors and audi...  d432056d-a4cb-11ef-a0e5-346f24a52a12.wav
spencer-015   As morning sunbeams pierced the forest canopy, ...  f5cec8b9-a4ca-11ef-a7e0-346f24a52a12.wav
              As negotiations concluded, key stakeholders cap...  a22cf8a0-a4cb-11ef-be8c-346f24a52a12.wav
              In contrast to yesterday's calmness, today's fo...  32f6e4db-a4cb-11ef-a12d-346f24a52a12.wav
              Innovative software applications have transform...  0366144c-a4cc-11ef-a62c-346f24a52a12.wav
              Meanwhile, across town, experts debated the imp...  40652bc7-a4cc-11ef-94e1-346f24a52a12.wav
              Oh, what a breathtaking sight the aurora boreal...  57434b8e-a4cb-11ef-804b-346f24a52a12.wav
              The finance minister disclosed the budget cuts ...  b9f34e5f-a4cb-11ef-aa8b-346f24a52a12.wav
              The stormy weather brought heavy rainfall and s...  1252a030-a4cb-11ef-af46-346f24a52a12.wav
              The vast expanse of the Grand Canyon revealed h...  7b7649f2-a4cb-11ef-a647-346f24a52a12.wav
              Under close supervision from investors and audi...  df8dcda0-a4cb-11ef-8973-346f24a52a12.wav
vincent-001   As morning sunbeams pierced the forest canopy, ...  f9d56853-a4ca-11ef-a512-346f24a52a12.wav
              As negotiations concluded, key stakeholders cap...  a4b8969a-a4cb-11ef-97e6-346f24a52a12.wav
              In contrast to yesterday's calmness, today's fo...  3764995d-a4cb-11ef-8477-346f24a52a12.wav
              Innovative software applications have transform...  0c538ba3-a4cc-11ef-aa71-346f24a52a12.wav
              Meanwhile, across town, experts debated the imp...  46e9dcc7-a4cc-11ef-a2f1-346f24a52a12.wav
              Oh, what a breathtaking sight the aurora boreal...  5ed44eb9-a4cb-11ef-b82f-346f24a52a12.wav
              The finance minister disclosed the budget cuts ...  c26b2152-a4cb-11ef-88a3-346f24a52a12.wav
              The stormy weather brought heavy rainfall and s...  15a93607-a4cb-11ef-96dd-346f24a52a12.wav
              The vast expanse of the Grand Canyon revealed h...  8213df7f-a4cb-11ef-95e9-346f24a52a12.wav
              Under close supervision from investors and audi...  e0daf1d0-a4cb-11ef-9199-346f24a52a12.wav

                                                                                                          gpt_codes
speaker_id    text
LJ001-0001    As morning sunbeams pierced the forest canopy, ...  [85, 59, 256, 280, 630, 243, 258, 640, 76, 365...
              As negotiations concluded, key stakeholders cap...  [442, 323, 68, 635, 186, 422, 266, 701, 767, 3...
              In contrast to yesterday's calmness, today's fo...  [551, 99, 640, 70, 225, 571, 487, 74, 59, 294,...
              Innovative software applications have transform...  [831, 225, 627, 82, 171, 369, 767, 323, 8, 438...
              Meanwhile, across town, experts debated the imp...  [551, 627, 191, 392, 8, 90, 30, 69, 272, 53, 1...
              Oh, what a breathtaking sight the aurora boreal...  [637, 831, 74, 225, 76, 56, 258, 419, 263, 466...
              The finance minister disclosed the budget cuts ...  [534, 516, 488, 437, 487, 59, 655, 119, 221, 3...
              The stormy weather brought heavy rainfall and s...  [551, 369, 783, 756, 281, 28, 627, 225, 487, 7...
              The vast expanse of the Grand Canyon revealed h...  [551, 256, 692, 200, 294, 487, 28, 225, 76, 41...
              Under close supervision from investors and audi...  [442, 59, 527, 638, 405, 424, 729, 836, 551, 5...
constance-035 As morning sunbeams pierced the forest canopy, ...  [54, 85, 492, 983, 442, 105, 40, 280, 243, 115...
              As negotiations concluded, key stakeholders cap...  [442, 68, 655, 767, 231, 560, 438, 171, 369, 3...
              In contrast to yesterday's calmness, today's fo...  [808, 369, 527, 822, 217, 459, 290, 105, 225, ...
              Innovative software applications have transform...  [412, 28, 325, 256, 573, 200, 333, 160, 501, 3...
              Meanwhile, across town, experts debated the imp...  [698, 368, 280, 28, 1003, 31, 243, 131, 713, 2...
              Oh, what a breathtaking sight the aurora boreal...  [442, 487, 225, 56, 775, 30, 419, 627, 701, 55...
              The finance minister disclosed the budget cuts ...  [831, 105, 571, 297, 225, 12, 487, 325, 438, 3...
              The stormy weather brought heavy rainfall and s...  [701, 630, 783, 583, 73, 484, 627, 225, 105, 2...
              The vast expanse of the Grand Canyon revealed h...  [729, 256, 406, 432, 661, 59, 487, 28, 76, 225...
              Under close supervision from investors and audi...  [551, 12, 627, 31, 225, 365, 804, 538, 401, 76...
samantha-008  As morning sunbeams pierced the forest canopy, ...  [637, 323, 655, 273, 231, 453, 440, 561, 419, ...
              As negotiations concluded, key stakeholders cap...  [831, 40, 28, 225, 640, 609, 551, 369, 266, 21...
              In contrast to yesterday's calmness, today's fo...  [856, 333, 270, 630, 93, 295, 841, 290, 225, 4...
              Innovative software applications have transform...  [701, 28, 627, 225, 640, 8, 40, 369, 137, 510,...
              Meanwhile, across town, experts debated the imp...  [551, 277, 508, 304, 11, 92, 820, 706, 50, 10,...
              Oh, what a breathtaking sight the aurora boreal...  [538, 74, 258, 640, 14, 254, 744, 239, 70, 412...
              The finance minister disclosed the budget cuts ...  [640, 323, 401, 836, 481, 53, 68, 440, 313, 17...
              The stormy weather brought heavy rainfall and s...  [476, 11, 756, 810, 731, 469, 323, 69, 53, 267...
              The vast expanse of the Grand Canyon revealed h...  [571, 323, 171, 518, 767, 655, 40, 28, 225, 58...
              Under close supervision from investors and audi...  [637, 74, 640, 8, 128, 225, 76, 804, 538, 911,...
spencer-015   As morning sunbeams pierced the forest canopy, ...  [538, 72, 389, 128, 31, 210, 619, 69, 727, 145...
              As negotiations concluded, key stakeholders cap...  [534, 173, 389, 128, 436, 214, 65, 900, 375, 6...
              In contrast to yesterday's calmness, today's fo...  [308, 416, 440, 11, 214, 879, 171, 173, 323, 6...
              Innovative software applications have transform...  [308, 508, 368, 479, 62, 605, 619, 65, 292, 37...
              Meanwhile, across town, experts debated the imp...  [535, 210, 266, 369, 440, 126, 321, 69, 679, 7...
              Oh, what a breathtaking sight the aurora boreal...  [365, 230, 323, 561, 266, 69, 318, 699, 483, 7...
              The finance minister disclosed the budget cuts ...  [70, 93, 305, 675, 322, 12, 230, 587, 728, 880...
              The stormy weather brought heavy rainfall and s...  [610, 37, 751, 397, 622, 101, 841, 66, 342, 32...
              The vast expanse of the Grand Canyon revealed h...  [612, 444, 587, 559, 540, 638, 725, 158, 323, ...
              Under close supervision from investors and audi...  [538, 601, 11, 210, 292, 462, 385, 534, 489, 2...
vincent-001   As morning sunbeams pierced the forest canopy, ...  [924, 725, 619, 454, 363, 210, 619, 69, 624, 1...
              As negotiations concluded, key stakeholders cap...  [637, 725, 389, 619, 4, 210, 82, 243, 350, 587...
              In contrast to yesterday's calmness, today's fo...  [551, 65, 210, 321, 315, 66, 389, 323, 11, 225...
              Innovative software applications have transform...  [815, 416, 440, 323, 362, 375, 66, 65, 434, 15...
              Meanwhile, across town, experts debated the imp...  [808, 2, 350, 65, 37, 257, 30, 342, 713, 842, ...
              Oh, what a breathtaking sight the aurora boreal...  [147, 62, 180, 129, 342, 2, 254, 197, 337, 442...
              The finance minister disclosed the budget cuts ...  [551, 37, 27, 567, 635, 53, 323, 440, 66, 587,...
              The stormy weather brought heavy rainfall and s...  [118, 66, 280, 95, 837, 277, 561, 733, 453, 83...
              The vast expanse of the Grand Canyon revealed h...  [168, 126, 37, 192, 375, 389, 158, 323, 692, 4...
              Under close supervision from investors and audi...  [494, 619, 11, 127, 62, 429, 651, 434, 8, 266,...

In [12]:
mel_cond_l = samples.groupby(['speaker_id', 'text']).nth(1)
mel_cond_l

                                                                 gen_id  \
speaker_id    text
LJ001-0001    As morning sunbeams pierced the forest canopy, ...      4
              As negotiations concluded, key stakeholders cap...      1
              In contrast to yesterday's calmness, today's fo...      0
              Innovative software applications have transform...      1
              Meanwhile, across town, experts debated the imp...      2
              Oh, what a breathtaking sight the aurora boreal...      2
              The finance minister disclosed the budget cuts ...      0
              The stormy weather brought heavy rainfall and s...      2
              The vast expanse of the Grand Canyon revealed h...      3
              Under close supervision from investors and audi...      1
constance-035 As morning sunbeams pierced the forest canopy, ...      1
              As negotiations concluded, key stakeholders cap...      3
              In contrast to yesterday's calmness, today's fo...      1
              Innovative software applications have transform...      2
              Meanwhile, across town, experts debated the imp...      3
              Oh, what a breathtaking sight the aurora boreal...      4
              The finance minister disclosed the budget cuts ...      4
              The stormy weather brought heavy rainfall and s...      2
              The vast expanse of the Grand Canyon revealed h...      2
              Under close supervision from investors and audi...      0
samantha-008  As morning sunbeams pierced the forest canopy, ...      2
              As negotiations concluded, key stakeholders cap...      4
              In contrast to yesterday's calmness, today's fo...      2
              Innovative software applications have transform...      1
              Meanwhile, across town, experts debated the imp...      0
              Oh, what a breathtaking sight the aurora boreal...      2
              The finance minister disclosed the budget cuts ...      3
              The stormy weather brought heavy rainfall and s...      1
              The vast expanse of the Grand Canyon revealed h...      4
              Under close supervision from investors and audi...      3
spencer-015   As morning sunbeams pierced the forest canopy, ...      1
              As negotiations concluded, key stakeholders cap...      3
              In contrast to yesterday's calmness, today's fo...      4
              Innovative software applications have transform...      0
              Meanwhile, across town, experts debated the imp...      3
              Oh, what a breathtaking sight the aurora boreal...      1
              The finance minister disclosed the budget cuts ...      3
              The stormy weather brought heavy rainfall and s...      2
              The vast expanse of the Grand Canyon revealed h...      1
              Under close supervision from investors and audi...      2
vincent-001   As morning sunbeams pierced the forest canopy, ...      0
              As negotiations concluded, key stakeholders cap...      4
              In contrast to yesterday's calmness, today's fo...      4
              Innovative software applications have transform...      2
              Meanwhile, across town, experts debated the imp...      2
              Oh, what a breathtaking sight the aurora boreal...      0
              The finance minister disclosed the budget cuts ...      1
              The stormy weather brought heavy rainfall and s...      2
              The vast expanse of the Grand Canyon revealed h...      2
              Under close supervision from investors and audi...      3

                                                                                                  audio_id  \
speaker_id    text
LJ001-0001    As morning sunbeams pierced the forest canopy, ...  e8cd4603-a4ca-11ef-a789-346f24a52a12.wav
              As negotiations concluded, key stakeholders cap...  901cf6a8-a4cb-11ef-9b0f-346f24a52a12.wav
              In contrast to yesterday's calmness, today's fo...  211ff31d-a4cb-11ef-8c3a-346f24a52a12.wav
              Innovative software applications have transform...  f136366c-a4cb-11ef-8475-346f24a52a12.wav
              Meanwhile, across town, experts debated the imp...  2dd40b2a-a4cc-11ef-bbd1-346f24a52a12.wav
              Oh, what a breathtaking sight the aurora boreal...  46893bc9-a4cb-11ef-932c-346f24a52a12.wav
              The finance minister disclosed the budget cuts ...  aea1d090-a4cb-11ef-8eee-346f24a52a12.wav
              The stormy weather brought heavy rainfall and s...  061643de-a4cb-11ef-9b54-346f24a52a12.wav
              The vast expanse of the Grand Canyon revealed h...  6d25e9dc-a4cb-11ef-b4d0-346f24a52a12.wav
              Under close supervision from investors and audi...  cd12424a-a4cb-11ef-9d62-346f24a52a12.wav
constance-035 As morning sunbeams pierced the forest canopy, ...  de61bef4-a4ca-11ef-adc2-346f24a52a12.wav
              As negotiations concluded, key stakeholders cap...  8be32aa9-a4cb-11ef-b7f5-346f24a52a12.wav
              In contrast to yesterday's calmness, today's fo...  1ba887c6-a4cb-11ef-b900-346f24a52a12.wav
              Innovative software applications have transform...  ebaa8132-a4cb-11ef-a7a6-346f24a52a12.wav
              Meanwhile, across town, experts debated the imp...  1e26a485-a4cc-11ef-902d-346f24a52a12.wav
              Oh, what a breathtaking sight the aurora boreal...  42da328b-a4cb-11ef-acd0-346f24a52a12.wav
              The finance minister disclosed the budget cuts ...  adbc3166-a4cb-11ef-b0e5-346f24a52a12.wav
              The stormy weather brought heavy rainfall and s...  00d5b685-a4cb-11ef-892e-346f24a52a12.wav
              The vast expanse of the Grand Canyon revealed h...  6372dc87-a4cb-11ef-bf39-346f24a52a12.wav
              Under close supervision from investors and audi...  c3c908ef-a4cb-11ef-8ef7-346f24a52a12.wav
samantha-008  As morning sunbeams pierced the forest canopy, ...  ecd6b910-a4ca-11ef-850a-346f24a52a12.wav
              As negotiations concluded, key stakeholders cap...  9af7262e-a4cb-11ef-8447-346f24a52a12.wav
              In contrast to yesterday's calmness, today's fo...  2b19f13f-a4cb-11ef-bacc-346f24a52a12.wav
              Innovative software applications have transform...  f8a2ec5a-a4cb-11ef-b4c2-346f24a52a12.wav
              Meanwhile, across town, experts debated the imp...  372fde11-a4cc-11ef-8636-346f24a52a12.wav
              Oh, what a breathtaking sight the aurora boreal...  4cc20751-a4cb-11ef-acdf-346f24a52a12.wav
              The finance minister disclosed the budget cuts ...  b6cc3505-a4cb-11ef-8c46-346f24a52a12.wav
              The stormy weather brought heavy rainfall and s...  0add6843-a4cb-11ef-b241-346f24a52a12.wav
              The vast expanse of the Grand Canyon revealed h...  765a50c4-a4cb-11ef-b2ce-346f24a52a12.wav
              Under close supervision from investors and audi...  d6d95e49-a4cb-11ef-91f7-346f24a52a12.wav
spencer-015   As morning sunbeams pierced the forest canopy, ...  f2f6e19e-a4ca-11ef-99f6-346f24a52a12.wav
              As negotiations concluded, key stakeholders cap...  a0ca1fa7-a4cb-11ef-9b59-346f24a52a12.wav
              In contrast to yesterday's calmness, today's fo...  3613eec7-a4cb-11ef-9ab5-346f24a52a12.wav
              Innovative software applications have transform...  fe94fd06-a4cb-11ef-892a-346f24a52a12.wav
              Meanwhile, across town, experts debated the imp...  43a68800-a4cc-11ef-acb3-346f24a52a12.wav
              Oh, what a breathtaking sight the aurora boreal...  52420a78-a4cb-11ef-8e80-346f24a52a12.wav
              The finance minister disclosed the budget cuts ...  bc9ac16c-a4cb-11ef-86f7-346f24a52a12.wav
              The stormy weather brought heavy rainfall and s...  114c2cc7-a4cb-11ef-b372-346f24a52a12.wav
              The vast expanse of the Grand Canyon revealed h...  79e2b9f5-a4cb-11ef-b673-346f24a52a12.wav
              Under close supervision from investors and audi...  dcb6427c-a4cb-11ef-a305-346f24a52a12.wav
vincent-001   As morning sunbeams pierced the forest canopy, ...  f854fbff-a4ca-11ef-9007-346f24a52a12.wav
              As negotiations concluded, key stakeholders cap...  a88aed2d-a4cb-11ef-94ea-346f24a52a12.wav
              In contrast to yesterday's calmness, today's fo...  3c922bbe-a4cb-11ef-b44c-346f24a52a12.wav
              Innovative software applications have transform...  0975a50e-a4cc-11ef-9297-346f24a52a12.wav
              Meanwhile, across town, experts debated the imp...  4aa98f55-a4cc-11ef-ba33-346f24a52a12.wav
              Oh, what a breathtaking sight the aurora boreal...  58f31635-a4cb-11ef-b639-346f24a52a12.wav
              The finance minister disclosed the budget cuts ...  bfc109cf-a4cb-11ef-a15e-346f24a52a12.wav
              The stormy weather brought heavy rainfall and s...  16d27dd1-a4cb-11ef-ba05-346f24a52a12.wav
              The vast expanse of the Grand Canyon revealed h...  833abc91-a4cb-11ef-bf84-346f24a52a12.wav
              Under close supervision from investors and audi...  e5a3b571-a4cb-11ef-9da1-346f24a52a12.wav

                                                                                                          gpt_codes
speaker_id    text
LJ001-0001    As morning sunbeams pierced the forest canopy, ...  [442, 323, 81, 186, 527, 391, 258, 76, 487, 29...
              As negotiations concluded, key stakeholders cap...  [76, 59, 655, 68, 280, 527, 405, 155, 369, 767...
              In contrast to yesterday's calmness, today's fo...  [534, 333, 336, 421, 640, 841, 59, 323, 68, 68...
              Innovative software applications have transform...  [551, 28, 627, 225, 99, 368, 256, 333, 219, 8,...
              Meanwhile, across town, experts debated the imp...  [551, 225, 392, 28, 270, 561, 69, 272, 53, 423...
              Oh, what a breathtaking sight the aurora boreal...  [442, 225, 76, 258, 301, 30, 263, 466, 551, 83...
              The finance minister disclosed the budget cuts ...  [551, 171, 85, 347, 74, 59, 40, 119, 573, 323,...
              The stormy weather brought heavy rainfall and s...  [808, 405, 756, 583, 281, 437, 369, 30, 323, 4...
              The vast expanse of the Grand Canyon revealed h...  [551, 323, 272, 186, 68, 59, 28, 225, 76, 244,...
              Under close supervision from investors and audi...  [118, 856, 958, 225, 627, 630, 256, 329, 831, ...
constance-035 As morning sunbeams pierced the forest canopy, ...  [76, 40, 584, 474, 527, 115, 728, 640, 534, 22...
              As negotiations concluded, key stakeholders cap...  [442, 323, 68, 4, 415, 421, 266, 21, 155, 767,...
              In contrast to yesterday's calmness, today's fo...  [701, 325, 527, 875, 225, 534, 290, 74, 28, 68...
              Innovative software applications have transform...  [551, 392, 225, 28, 422, 369, 256, 333, 83, 8,...
              Meanwhile, across town, experts debated the imp...  [698, 40, 28, 82, 368, 626, 453, 207, 706, 50,...
              Oh, what a breathtaking sight the aurora boreal...  [831, 225, 13, 41, 571, 640, 262, 466, 121, 74...
              The finance minister disclosed the budget cuts ...  [831, 487, 841, 807, 365, 225, 290, 40, 407, 6...
              The stormy weather brought heavy rainfall and s...  [808, 405, 4, 756, 705, 493, 99, 640, 225, 627...
              The vast expanse of the Grand Canyon revealed h...  [831, 487, 432, 0, 627, 225, 28, 76, 41, 571, ...
              Under close supervision from investors and audi...  [442, 12, 640, 44, 225, 76, 804, 551, 524, 831...
samantha-008  As morning sunbeams pierced the forest canopy, ...  [831, 655, 584, 767, 280, 415, 26, 559, 17, 76...
              As negotiations concluded, key stakeholders cap...  [831, 323, 584, 40, 205, 231, 115, 405, 508, 2...
              In contrast to yesterday's calmness, today's fo...  [551, 266, 440, 11, 538, 271, 53, 272, 7, 92, ...
              Innovative software applications have transform...  [882, 28, 8, 225, 640, 205, 40, 333, 160, 662,...
              Meanwhile, across town, experts debated the imp...  [698, 368, 280, 28, 1003, 243, 453, 7, 10, 706...
              Oh, what a breathtaking sight the aurora boreal...  [538, 74, 225, 627, 496, 423, 511, 483, 239, 7...
              The finance minister disclosed the budget cuts ...  [551, 53, 457, 524, 59, 323, 655, 453, 313, 27...
              The stormy weather brought heavy rainfall and s...  [571, 405, 205, 756, 102, 244, 28, 640, 225, 9...
              The vast expanse of the Grand Canyon revealed h...  [551, 655, 53, 11, 75, 767, 288, 487, 28, 225,...
              Under close supervision from investors and audi...  [831, 74, 8, 243, 128, 105, 721, 729, 217, 768...
spencer-015   As morning sunbeams pierced the forest canopy, ...  [365, 18, 587, 403, 4, 243, 210, 29, 275, 727,...
              As negotiations concluded, key stakeholders cap...  [365, 18, 18, 880, 544, 360, 560, 133, 61, 505...
              In contrast to yesterday's calmness, today's fo...  [872, 11, 210, 337, 295, 594, 323, 59, 625, 42...
              Innovative software applications have transform...  [308, 266, 794, 158, 467, 128, 639, 554, 294, ...
              Meanwhile, across town, experts debated the imp...  [339, 210, 158, 266, 416, 209, 257, 69, 226, 7...
              Oh, what a breathtaking sight the aurora boreal...  [551, 258, 7, 342, 66, 820, 318, 262, 699, 744...
              The finance minister disclosed the budget cuts ...  [385, 451, 545, 1, 322, 529, 328, 587, 363, 44...
              The stormy weather brought heavy rainfall and s...  [610, 37, 474, 397, 191, 427, 266, 30, 248, 55...
              The vast expanse of the Grand Canyon revealed h...  [303, 108, 296, 183, 142, 135, 321, 450, 105, ...
              Under close supervision from investors and audi...  [357, 727, 372, 410, 91, 289, 717, 551, 16, 14...
vincent-001   As morning sunbeams pierced the forest canopy, ...  [538, 725, 269, 4, 210, 210, 619, 69, 581, 145...
              As negotiations concluded, key stakeholders cap...  [551, 725, 269, 4, 210, 82, 243, 65, 619, 323,...
              In contrast to yesterday's calmness, today's fo...  [882, 416, 11, 66, 225, 605, 323, 727, 440, 36...
              Innovative software applications have transform...  [856, 416, 440, 323, 210, 375, 266, 158, 83, 1...
              Meanwhile, across town, experts debated the imp...  [551, 2, 269, 199, 129, 275, 342, 611, 795, 84...
              Oh, what a breathtaking sight the aurora boreal...  [385, 62, 496, 728, 342, 307, 463, 744, 672, 5...
              The finance minister disclosed the budget cuts ...  [551, 129, 826, 920, 230, 7, 323, 440, 266, 31...
              The stormy weather brought heavy rainfall and s...  [905, 37, 454, 622, 346, 273, 53, 323, 440, 26...
              The vast expanse of the Grand Canyon revealed h...  [815, 37, 471, 414, 167, 725, 389, 323, 53, 43...
              Under close supervision from investors and audi...  [551, 56, 210, 403, 37, 753, 640, 618, 820, 26...

In [14]:
(mel_cond_w['gen_id'] == mel_cond_l['gen_id']).sum()

0

In [16]:
df = mel_cond_w.copy()
df.rename(columns={'gpt_codes': 'mel_cond_w'}, inplace=True)
df.drop(columns=['gen_id'], inplace=True)

df['mel_cond_l'] = mel_cond_l['gpt_codes']
df

                                                                                                  audio_id  \
speaker_id    text
LJ001-0001    As morning sunbeams pierced the forest canopy, ...  e4f364e1-a4ca-11ef-b0f6-346f24a52a12.wav
              As negotiations concluded, key stakeholders cap...  92b49ff6-a4cb-11ef-83b7-346f24a52a12.wav
              In contrast to yesterday's calmness, today's fo...  227f7427-a4cb-11ef-b78f-346f24a52a12.wav
              Innovative software applications have transform...  efec9fcb-a4cb-11ef-8fb1-346f24a52a12.wav
              Meanwhile, across town, experts debated the imp...  267c2f6c-a4cc-11ef-8bb1-346f24a52a12.wav
              Oh, what a breathtaking sight the aurora boreal...  48dfbed8-a4cb-11ef-9ca7-346f24a52a12.wav
              The finance minister disclosed the budget cuts ...  b06cade4-a4cb-11ef-9df3-346f24a52a12.wav
              The stormy weather brought heavy rainfall and s...  05072a7e-a4cb-11ef-b2a0-346f24a52a12.wav
              The vast expanse of the Grand Canyon revealed h...  688b2755-a4cb-11ef-a9ec-346f24a52a12.wav
              Under close supervision from investors and audi...  cbaaf6b1-a4cb-11ef-a9c0-346f24a52a12.wav
constance-035 As morning sunbeams pierced the forest canopy, ...  dd116c13-a4ca-11ef-a829-346f24a52a12.wav
              As negotiations concluded, key stakeholders cap...  89377c5f-a4cb-11ef-8714-346f24a52a12.wav
              In contrast to yesterday's calmness, today's fo...  1e94b196-a4cb-11ef-84a0-346f24a52a12.wav
              Innovative software applications have transform...  eeb523d5-a4cb-11ef-8adb-346f24a52a12.wav
              Meanwhile, across town, experts debated the imp...  1a917e08-a4cc-11ef-bfe3-346f24a52a12.wav
              Oh, what a breathtaking sight the aurora boreal...  3dccddf6-a4cb-11ef-9dc1-346f24a52a12.wav
              The finance minister disclosed the budget cuts ...  aaa48b9e-a4cb-11ef-bc2f-346f24a52a12.wav
              The stormy weather brought heavy rainfall and s...  030f39c0-a4cb-11ef-8716-346f24a52a12.wav
              The vast expanse of the Grand Canyon revealed h...  6029f2de-a4cb-11ef-ad9d-346f24a52a12.wav
              Under close supervision from investors and audi...  c75a6817-a4cb-11ef-886c-346f24a52a12.wav
samantha-008  As morning sunbeams pierced the forest canopy, ...  ea1cf566-a4ca-11ef-b954-346f24a52a12.wav
              As negotiations concluded, key stakeholders cap...  95627b68-a4cb-11ef-a310-346f24a52a12.wav
              In contrast to yesterday's calmness, today's fo...  2e6ddc61-a4cb-11ef-a85c-346f24a52a12.wav
              Innovative software applications have transform...  f9e5e637-a4cb-11ef-8f88-346f24a52a12.wav
              Meanwhile, across town, experts debated the imp...  3a216622-a4cc-11ef-877f-346f24a52a12.wav
              Oh, what a breathtaking sight the aurora boreal...  4b8399c6-a4cb-11ef-95f0-346f24a52a12.wav
              The finance minister disclosed the budget cuts ...  b47017ed-a4cb-11ef-ad64-346f24a52a12.wav
              The stormy weather brought heavy rainfall and s...  0ce3d647-a4cb-11ef-b627-346f24a52a12.wav
              The vast expanse of the Grand Canyon revealed h...  71cb90ca-a4cb-11ef-95e7-346f24a52a12.wav
              Under close supervision from investors and audi...  d432056d-a4cb-11ef-a0e5-346f24a52a12.wav
spencer-015   As morning sunbeams pierced the forest canopy, ...  f5cec8b9-a4ca-11ef-a7e0-346f24a52a12.wav
              As negotiations concluded, key stakeholders cap...  a22cf8a0-a4cb-11ef-be8c-346f24a52a12.wav
              In contrast to yesterday's calmness, today's fo...  32f6e4db-a4cb-11ef-a12d-346f24a52a12.wav
              Innovative software applications have transform...  0366144c-a4cc-11ef-a62c-346f24a52a12.wav
              Meanwhile, across town, experts debated the imp...  40652bc7-a4cc-11ef-94e1-346f24a52a12.wav
              Oh, what a breathtaking sight the aurora boreal...  57434b8e-a4cb-11ef-804b-346f24a52a12.wav
              The finance minister disclosed the budget cuts ...  b9f34e5f-a4cb-11ef-aa8b-346f24a52a12.wav
              The stormy weather brought heavy rainfall and s...  1252a030-a4cb-11ef-af46-346f24a52a12.wav
              The vast expanse of the Grand Canyon revealed h...  7b7649f2-a4cb-11ef-a647-346f24a52a12.wav
              Under close supervision from investors and audi...  df8dcda0-a4cb-11ef-8973-346f24a52a12.wav
vincent-001   As morning sunbeams pierced the forest canopy, ...  f9d56853-a4ca-11ef-a512-346f24a52a12.wav
              As negotiations concluded, key stakeholders cap...  a4b8969a-a4cb-11ef-97e6-346f24a52a12.wav
              In contrast to yesterday's calmness, today's fo...  3764995d-a4cb-11ef-8477-346f24a52a12.wav
              Innovative software applications have transform...  0c538ba3-a4cc-11ef-aa71-346f24a52a12.wav
              Meanwhile, across town, experts debated the imp...  46e9dcc7-a4cc-11ef-a2f1-346f24a52a12.wav
              Oh, what a breathtaking sight the aurora boreal...  5ed44eb9-a4cb-11ef-b82f-346f24a52a12.wav
              The finance minister disclosed the budget cuts ...  c26b2152-a4cb-11ef-88a3-346f24a52a12.wav
              The stormy weather brought heavy rainfall and s...  15a93607-a4cb-11ef-96dd-346f24a52a12.wav
              The vast expanse of the Grand Canyon revealed h...  8213df7f-a4cb-11ef-95e9-346f24a52a12.wav
              Under close supervision from investors and audi...  e0daf1d0-a4cb-11ef-9199-346f24a52a12.wav

                                                                                                         mel_cond_w  \
speaker_id    text
LJ001-0001    As morning sunbeams pierced the forest canopy, ...  [85, 59, 256, 280, 630, 243, 258, 640, 76, 365...
              As negotiations concluded, key stakeholders cap...  [442, 323, 68, 635, 186, 422, 266, 701, 767, 3...
              In contrast to yesterday's calmness, today's fo...  [551, 99, 640, 70, 225, 571, 487, 74, 59, 294,...
              Innovative software applications have transform...  [831, 225, 627, 82, 171, 369, 767, 323, 8, 438...
              Meanwhile, across town, experts debated the imp...  [551, 627, 191, 392, 8, 90, 30, 69, 272, 53, 1...
              Oh, what a breathtaking sight the aurora boreal...  [637, 831, 74, 225, 76, 56, 258, 419, 263, 466...
              The finance minister disclosed the budget cuts ...  [534, 516, 488, 437, 487, 59, 655, 119, 221, 3...
              The stormy weather brought heavy rainfall and s...  [551, 369, 783, 756, 281, 28, 627, 225, 487, 7...
              The vast expanse of the Grand Canyon revealed h...  [551, 256, 692, 200, 294, 487, 28, 225, 76, 41...
              Under close supervision from investors and audi...  [442, 59, 527, 638, 405, 424, 729, 836, 551, 5...
constance-035 As morning sunbeams pierced the forest canopy, ...  [54, 85, 492, 983, 442, 105, 40, 280, 243, 115...
              As negotiations concluded, key stakeholders cap...  [442, 68, 655, 767, 231, 560, 438, 171, 369, 3...
              In contrast to yesterday's calmness, today's fo...  [808, 369, 527, 822, 217, 459, 290, 105, 225, ...
              Innovative software applications have transform...  [412, 28, 325, 256, 573, 200, 333, 160, 501, 3...
              Meanwhile, across town, experts debated the imp...  [698, 368, 280, 28, 1003, 31, 243, 131, 713, 2...
              Oh, what a breathtaking sight the aurora boreal...  [442, 487, 225, 56, 775, 30, 419, 627, 701, 55...
              The finance minister disclosed the budget cuts ...  [831, 105, 571, 297, 225, 12, 487, 325, 438, 3...
              The stormy weather brought heavy rainfall and s...  [701, 630, 783, 583, 73, 484, 627, 225, 105, 2...
              The vast expanse of the Grand Canyon revealed h...  [729, 256, 406, 432, 661, 59, 487, 28, 76, 225...
              Under close supervision from investors and audi...  [551, 12, 627, 31, 225, 365, 804, 538, 401, 76...
samantha-008  As morning sunbeams pierced the forest canopy, ...  [637, 323, 655, 273, 231, 453, 440, 561, 419, ...
              As negotiations concluded, key stakeholders cap...  [831, 40, 28, 225, 640, 609, 551, 369, 266, 21...
              In contrast to yesterday's calmness, today's fo...  [856, 333, 270, 630, 93, 295, 841, 290, 225, 4...
              Innovative software applications have transform...  [701, 28, 627, 225, 640, 8, 40, 369, 137, 510,...
              Meanwhile, across town, experts debated the imp...  [551, 277, 508, 304, 11, 92, 820, 706, 50, 10,...
              Oh, what a breathtaking sight the aurora boreal...  [538, 74, 258, 640, 14, 254, 744, 239, 70, 412...
              The finance minister disclosed the budget cuts ...  [640, 323, 401, 836, 481, 53, 68, 440, 313, 17...
              The stormy weather brought heavy rainfall and s...  [476, 11, 756, 810, 731, 469, 323, 69, 53, 267...
              The vast expanse of the Grand Canyon revealed h...  [571, 323, 171, 518, 767, 655, 40, 28, 225, 58...
              Under close supervision from investors and audi...  [637, 74, 640, 8, 128, 225, 76, 804, 538, 911,...
spencer-015   As morning sunbeams pierced the forest canopy, ...  [538, 72, 389, 128, 31, 210, 619, 69, 727, 145...
              As negotiations concluded, key stakeholders cap...  [534, 173, 389, 128, 436, 214, 65, 900, 375, 6...
              In contrast to yesterday's calmness, today's fo...  [308, 416, 440, 11, 214, 879, 171, 173, 323, 6...
              Innovative software applications have transform...  [308, 508, 368, 479, 62, 605, 619, 65, 292, 37...
              Meanwhile, across town, experts debated the imp...  [535, 210, 266, 369, 440, 126, 321, 69, 679, 7...
              Oh, what a breathtaking sight the aurora boreal...  [365, 230, 323, 561, 266, 69, 318, 699, 483, 7...
              The finance minister disclosed the budget cuts ...  [70, 93, 305, 675, 322, 12, 230, 587, 728, 880...
              The stormy weather brought heavy rainfall and s...  [610, 37, 751, 397, 622, 101, 841, 66, 342, 32...
              The vast expanse of the Grand Canyon revealed h...  [612, 444, 587, 559, 540, 638, 725, 158, 323, ...
              Under close supervision from investors and audi...  [538, 601, 11, 210, 292, 462, 385, 534, 489, 2...
vincent-001   As morning sunbeams pierced the forest canopy, ...  [924, 725, 619, 454, 363, 210, 619, 69, 624, 1...
              As negotiations concluded, key stakeholders cap...  [637, 725, 389, 619, 4, 210, 82, 243, 350, 587...
              In contrast to yesterday's calmness, today's fo...  [551, 65, 210, 321, 315, 66, 389, 323, 11, 225...
              Innovative software applications have transform...  [815, 416, 440, 323, 362, 375, 66, 65, 434, 15...
              Meanwhile, across town, experts debated the imp...  [808, 2, 350, 65, 37, 257, 30, 342, 713, 842, ...
              Oh, what a breathtaking sight the aurora boreal...  [147, 62, 180, 129, 342, 2, 254, 197, 337, 442...
              The finance minister disclosed the budget cuts ...  [551, 37, 27, 567, 635, 53, 323, 440, 66, 587,...
              The stormy weather brought heavy rainfall and s...  [118, 66, 280, 95, 837, 277, 561, 733, 453, 83...
              The vast expanse of the Grand Canyon revealed h...  [168, 126, 37, 192, 375, 389, 158, 323, 692, 4...
              Under close supervision from investors and audi...  [494, 619, 11, 127, 62, 429, 651, 434, 8, 266,...

                                                                                                         mel_cond_l
speaker_id    text
LJ001-0001    As morning sunbeams pierced the forest canopy, ...  [442, 323, 81, 186, 527, 391, 258, 76, 487, 29...
              As negotiations concluded, key stakeholders cap...  [76, 59, 655, 68, 280, 527, 405, 155, 369, 767...
              In contrast to yesterday's calmness, today's fo...  [534, 333, 336, 421, 640, 841, 59, 323, 68, 68...
              Innovative software applications have transform...  [551, 28, 627, 225, 99, 368, 256, 333, 219, 8,...
              Meanwhile, across town, experts debated the imp...  [551, 225, 392, 28, 270, 561, 69, 272, 53, 423...
              Oh, what a breathtaking sight the aurora boreal...  [442, 225, 76, 258, 301, 30, 263, 466, 551, 83...
              The finance minister disclosed the budget cuts ...  [551, 171, 85, 347, 74, 59, 40, 119, 573, 323,...
              The stormy weather brought heavy rainfall and s...  [808, 405, 756, 583, 281, 437, 369, 30, 323, 4...
              The vast expanse of the Grand Canyon revealed h...  [551, 323, 272, 186, 68, 59, 28, 225, 76, 244,...
              Under close supervision from investors and audi...  [118, 856, 958, 225, 627, 630, 256, 329, 831, ...
constance-035 As morning sunbeams pierced the forest canopy, ...  [76, 40, 584, 474, 527, 115, 728, 640, 534, 22...
              As negotiations concluded, key stakeholders cap...  [442, 323, 68, 4, 415, 421, 266, 21, 155, 767,...
              In contrast to yesterday's calmness, today's fo...  [701, 325, 527, 875, 225, 534, 290, 74, 28, 68...
              Innovative software applications have transform...  [551, 392, 225, 28, 422, 369, 256, 333, 83, 8,...
              Meanwhile, across town, experts debated the imp...  [698, 40, 28, 82, 368, 626, 453, 207, 706, 50,...
              Oh, what a breathtaking sight the aurora boreal...  [831, 225, 13, 41, 571, 640, 262, 466, 121, 74...
              The finance minister disclosed the budget cuts ...  [831, 487, 841, 807, 365, 225, 290, 40, 407, 6...
              The stormy weather brought heavy rainfall and s...  [808, 405, 4, 756, 705, 493, 99, 640, 225, 627...
              The vast expanse of the Grand Canyon revealed h...  [831, 487, 432, 0, 627, 225, 28, 76, 41, 571, ...
              Under close supervision from investors and audi...  [442, 12, 640, 44, 225, 76, 804, 551, 524, 831...
samantha-008  As morning sunbeams pierced the forest canopy, ...  [831, 655, 584, 767, 280, 415, 26, 559, 17, 76...
              As negotiations concluded, key stakeholders cap...  [831, 323, 584, 40, 205, 231, 115, 405, 508, 2...
              In contrast to yesterday's calmness, today's fo...  [551, 266, 440, 11, 538, 271, 53, 272, 7, 92, ...
              Innovative software applications have transform...  [882, 28, 8, 225, 640, 205, 40, 333, 160, 662,...
              Meanwhile, across town, experts debated the imp...  [698, 368, 280, 28, 1003, 243, 453, 7, 10, 706...
              Oh, what a breathtaking sight the aurora boreal...  [538, 74, 225, 627, 496, 423, 511, 483, 239, 7...
              The finance minister disclosed the budget cuts ...  [551, 53, 457, 524, 59, 323, 655, 453, 313, 27...
              The stormy weather brought heavy rainfall and s...  [571, 405, 205, 756, 102, 244, 28, 640, 225, 9...
              The vast expanse of the Grand Canyon revealed h...  [551, 655, 53, 11, 75, 767, 288, 487, 28, 225,...
              Under close supervision from investors and audi...  [831, 74, 8, 243, 128, 105, 721, 729, 217, 768...
spencer-015   As morning sunbeams pierced the forest canopy, ...  [365, 18, 587, 403, 4, 243, 210, 29, 275, 727,...
              As negotiations concluded, key stakeholders cap...  [365, 18, 18, 880, 544, 360, 560, 133, 61, 505...
              In contrast to yesterday's calmness, today's fo...  [872, 11, 210, 337, 295, 594, 323, 59, 625, 42...
              Innovative software applications have transform...  [308, 266, 794, 158, 467, 128, 639, 554, 294, ...
              Meanwhile, across town, experts debated the imp...  [339, 210, 158, 266, 416, 209, 257, 69, 226, 7...
              Oh, what a breathtaking sight the aurora boreal...  [551, 258, 7, 342, 66, 820, 318, 262, 699, 744...
              The finance minister disclosed the budget cuts ...  [385, 451, 545, 1, 322, 529, 328, 587, 363, 44...
              The stormy weather brought heavy rainfall and s...  [610, 37, 474, 397, 191, 427, 266, 30, 248, 55...
              The vast expanse of the Grand Canyon revealed h...  [303, 108, 296, 183, 142, 135, 321, 450, 105, ...
              Under close supervision from investors and audi...  [357, 727, 372, 410, 91, 289, 717, 551, 16, 14...
vincent-001   As morning sunbeams pierced the forest canopy, ...  [538, 725, 269, 4, 210, 210, 619, 69, 581, 145...
              As negotiations concluded, key stakeholders cap...  [551, 725, 269, 4, 210, 82, 243, 65, 619, 323,...
              In contrast to yesterday's calmness, today's fo...  [882, 416, 11, 66, 225, 605, 323, 727, 440, 36...
              Innovative software applications have transform...  [856, 416, 440, 323, 210, 375, 266, 158, 83, 1...
              Meanwhile, across town, experts debated the imp...  [551, 2, 269, 199, 129, 275, 342, 611, 795, 84...
              Oh, what a breathtaking sight the aurora boreal...  [385, 62, 496, 728, 342, 307, 463, 744, 672, 5...
              The finance minister disclosed the budget cuts ...  [551, 129, 826, 920, 230, 7, 323, 440, 266, 31...
              The stormy weather brought heavy rainfall and s...  [905, 37, 454, 622, 346, 273, 53, 323, 440, 26...
              The vast expanse of the Grand Canyon revealed h...  [815, 37, 471, 414, 167, 725, 389, 323, 53, 43...
              Under close supervision from investors and audi...  [551, 56, 210, 403, 37, 753, 640, 618, 820, 26...

In [21]:
df.reset_index().to_parquet('../data/dpo_dataset/metadata.parquet')

In [22]:
df= pd.read_parquet('../data/dpo_dataset/metadata.parquet')
df

,speaker_id,text,audio_id,mel_cond_w,mel_cond_l
0,LJ001-0001,"As morning sunbeams pierced the forest canopy,...",e4f364e1-a4ca-11ef-b0f6-346f24a52a12.wav,"[85, 59, 256, 280, 630, 243, 258, 640, 76, 365...","[442, 323, 81, 186, 527, 391, 258, 76, 487, 29..."
1,LJ001-0001,"As negotiations concluded, key stakeholders ca...",92b49ff6-a4cb-11ef-83b7-346f24a52a12.wav,"[442, 323, 68, 635, 186, 422, 266, 701, 767, 3...","[76, 59, 655, 68, 280, 527, 405, 155, 369, 767..."
2,LJ001-0001,"In contrast to yesterday's calmness, today's f...",227f7427-a4cb-11ef-b78f-346f24a52a12.wav,"[551, 99, 640, 70, 225, 571, 487, 74, 59, 294,...","[534, 333, 336, 421, 640, 841, 59, 323, 68, 68..."
3,LJ001-0001,Innovative software applications have transfor...,efec9fcb-a4cb-11ef-8fb1-346f24a52a12.wav,"[831, 225, 627, 82, 171, 369, 767, 323, 8, 438...","[551, 28, 627, 225, 99, 368, 256, 333, 219, 8,..."
4,LJ001-0001,"Meanwhile, across town, experts debated the im...",267c2f6c-a4cc-11ef-8bb1-346f24a52a12.wav,"[551, 627, 191, 392, 8, 90, 30, 69, 272, 53, 1...","[551, 225, 392, 28, 270, 561, 69, 272, 53, 423..."
5,LJ001-0001,"Oh, what a breathtaking sight the aurora borea...",48dfbed8-a4cb-11ef-9ca7-346f24a52a12.wav,"[637, 831, 74, 225, 76, 56, 258, 419, 263, 466...","[442, 225, 76, 258, 301, 30, 263, 466, 551, 83..."
6,LJ001-0001,The finance minister disclosed the budget cuts...,b06cade4-a4cb-11ef-9df3-346f24a52a12.wav,"[534, 516, 488, 437, 487, 59, 655, 119, 221, 3...","[551, 171, 85, 347, 74, 59, 40, 119, 573, 323,..."
7,LJ001-0001,The stormy weather brought heavy rainfall and ...,05072a7e-a4cb-11ef-b2a0-346f24a52a12.wav,"[551, 369, 783, 756, 281, 28, 627, 225, 487, 7...","[808, 405, 756, 583, 281, 437, 369, 30, 323, 4..."
8,LJ001-0001,The vast expanse of the Grand Canyon revealed ...,688b2755-a4cb-11ef-a9ec-346f24a52a12.wav,"[551, 256, 692, 200, 294, 487, 28, 225, 76, 41...","[551, 323, 272, 186, 68, 59, 28, 225, 76, 244,..."
9,LJ001-0001,Under close supervision from investors and aud...,cbaaf6b1-a4cb-11ef-a9c0-346f24a52a12.wav,"[442, 59, 527, 638, 405, 424, 729, 836, 551, 5...","[118, 856, 958, 225, 627, 630, 256, 329, 831, ..."
10,constance-035,"As morning sunbeams pierced the forest canopy,...",dd116c13-a4ca-11ef-a829-346f24a52a12.wav,"[54, 85, 492, 983, 442, 105, 40, 280, 243, 115...","[76, 40, 584, 474, 527, 115, 728, 640, 534, 22..."
11,constance-035,"As negotiations concluded, key stakeholders ca...",89377c5f-a4cb-11ef-8714-346f24a52a12.wav,"[442, 68, 655, 767, 231, 560, 438, 171, 369, 3...","[442, 323, 68, 4, 415, 421, 266, 21, 155, 767,..."
12,constance-035,"In contrast to yesterday's calmness, today's f...",1e94b196-a4cb-11ef-84a0-346f24a52a12.wav,"[808, 369, 527, 822, 217, 459, 290, 105, 225, ...","[701, 325, 527, 875, 225, 534, 290, 74, 28, 68..."
13,constance-035,Innovative software applications have transfor...,eeb523d5-a4cb-11ef-8adb-346f24a52a12.wav,"[412, 28, 325, 256, 573, 200, 333, 160, 501, 3...","[551, 392, 225, 28, 422, 369, 256, 333, 83, 8,..."
14,constance-035,"Meanwhile, across town, experts debated the im...",1a917e08-a4cc-11ef-bfe3-346f24a52a12.wav,"[698, 368, 280, 28, 1003, 31, 243, 131, 713, 2...","[698, 40, 28, 82, 368, 626, 453, 207, 706, 50,..."
15,constance-035,"Oh, what a breathtaking sight the aurora borea...",3dccddf6-a4cb-11ef-9dc1-346f24a52a12.wav,"[442, 487, 225, 56, 775, 30, 419, 627, 701, 55...","[831, 225, 13, 41, 571, 640, 262, 466, 121, 74..."
16,constance-035,The finance minister disclosed the budget cuts...,aaa48b9e-a4cb-11ef-bc2f-346f24a52a12.wav,"[831, 105, 571, 297, 225, 12, 487, 325, 438, 3...","[831, 487, 841, 807, 365, 225, 290, 40, 407, 6..."
17,constance-035,The stormy weather brought heavy rainfall and ...,030f39c0-a4cb-11ef-8716-346f24a52a12.wav,"[701, 630, 783, 583, 73, 484, 627, 225, 105, 2...","[808, 405, 4, 756, 705, 493, 99, 640, 225, 627..."
18,constance-035,The vast expanse of the Grand Canyon revealed ...,6029f2de-a4cb-11ef-ad9d-346f24a52a12.wav,"[729, 256, 406, 432, 661, 59, 487, 28, 76, 225...","[831, 487, 432, 0, 627, 225, 28, 76, 41, 571, ..."
19,constance-035,Under close supervision from investors and aud...,c75a6817-a4cb-11ef-886c-346f24a52a12.wav,"[551, 12, 627, 31, 225, 365, 804, 538, 401, 76...","[442, 12, 640, 44, 225, 76, 804, 551, 524, 831..."
20,samantha-008,"As morning sunbeams pierced the forest canopy,...",ea1cf566-a4ca-11ef-b954-346f24a52a12.wav,"[637, 323, 655, 273, 231, 453, 440, 561, 419, ...","[831, 655, 584, 767, 280, 415, 26, 559, 17, 76..."
21,samantha-008,"As negotiations concluded, key stakeholders ca...",95627b68-a4cb-11ef-a310-346f24a52a12.wav,"[831, 40, 28, 225, 640, 609, 551, 369, 266, 21...","[831, 323, 584, 40, 205, 231, 115, 405, 508, 2..."
22,samantha-008,"In contrast to yesterday's calmness, today's f...",2e6ddc61-a4cb-11ef-a85c-346f24a52a12.wav,"[856, 333, 270, 630, 93, 295, 841, 290, 225, 4...","[551, 266, 440, 11, 538, 271, 53, 272, 7, 92, ..."
23,samantha-008,Innovative software applications have transfor...,f9e5e637-a4cb-11ef-8f88-346f24a52a12.wav,"[701, 28, 627, 225, 640, 8, 40, 369, 137, 510,...","[882, 28, 8, 225, 640, 205, 40, 333, 160, 662,..."
24,samantha-008,"Meanwhile, across town, experts debated the im...",3a216622-a4cc-11ef-877f-346f24a52a12.wav,"[551, 277, 508, 304, 11, 92, 820, 706, 50, 10,...","[698, 368, 280, 28, 1003, 243, 453, 7, 10, 706..."
25,samantha-008,"Oh, what a breathtaking sight the aurora borea...",4b8399c6-a4cb-11ef-95f0-346f24a52a12.wav,"[538, 74, 258, 640, 14, 254, 744, 239, 70, 412...","[538, 74, 225, 627, 496, 423, 511, 483, 239, 7..."
26,samantha-008,The finance minister disclosed the budget cuts...,b47017ed-a4cb-11ef-ad64-346f24a52a12.wav,"[640, 323, 401, 836, 481, 53, 68, 440, 313, 17...","[551, 53, 457, 524, 59, 323, 655, 453, 313, 27..."
27,samantha-008,The stormy weather brought heavy rainfall and ...,0ce3d647-a4cb-11ef-b627-346f24a52a12.wav,"[476, 11, 756, 810, 731, 469, 323, 69, 53, 267...","[571, 405, 205, 756, 102, 244, 28, 640, 225, 9..."
28,samantha-008,The vast expanse of the Grand Canyon revealed ...,71cb90ca-a4cb-11ef-95e7-346f24a52a12.wav,"[571, 323, 171, 518, 767, 655, 40, 28, 225, 58...","[551, 655, 53, 11, 75, 767, 288, 487, 28, 225,..."
29,samantha-008,Under close supervision from investors and aud...,d432056d-a4cb-11ef-a0e5-346f24a52a12.wav,"[637, 74, 640, 8, 128, 225, 76, 804, 538, 911,...","[831, 74, 8, 243, 128, 105, 721, 729, 217, 768..."
30,spencer-015,"As morning sunbeams pierced the forest canopy,...",f5cec8b9-a4ca-11ef-a7e0-346f24a52a12.wav,"[538, 72, 389, 128, 31, 210, 619, 69, 727, 145...","[365, 18, 587, 403, 4, 243, 210, 29, 275, 727,..."
31,spencer-015,"As negotiations concluded, key stakeholders ca...",a22cf8a0-a4cb-11ef-be8c-346f24a52a12.wav,"[534, 173, 389, 128, 436, 214, 65, 900, 375, 6...","[365, 18, 18, 880, 544, 360, 560, 133, 61, 505..."
32,spencer-015,"In contrast to yesterday's calmness, today's f...",32f6e4db-a4cb-11ef-a12d-346f24a52a12.wav,"[308, 416, 440, 11, 214, 879, 171, 173, 323, 6...","[872, 11, 210, 337, 295, 594, 323, 59, 625, 42..."
33,spencer-015,Innovative software applications have transfor...,0366144c-a4cc-11ef-a62c-346f24a52a12.wav,"[308, 508, 368, 479, 62, 605, 619, 65, 292, 37...","[308, 266, 794, 158, 467, 128, 639, 554, 294, ..."
34,spencer-015,"Meanwhile, across town, experts debated the im...",40652bc7-a4cc-11ef-94e1-346f24a52a12.wav,"[535, 210, 266, 369, 440, 126, 321, 69, 679, 7...","[339, 210, 158, 266, 416, 209, 257, 69, 226, 7..."
35,spencer-015,"Oh, what a breathtaking sight the aurora borea...",57434b8e-a4cb-11ef-804b-346f24a52a12.wav,"[365, 230, 323, 561, 266, 69, 318, 699, 483, 7...","[551, 258, 7, 342, 66, 820, 318, 262, 699, 744..."
36,spencer-015,The finance minister disclosed the budget cuts...,b9f34e5f-a4cb-11ef-aa8b-346f24a52a12.wav,"[70, 93, 305, 675, 322, 12, 230, 587, 728, 880...","[385, 451, 545, 1, 322, 529, 328, 587, 363, 44..."
37,spencer-015,The stormy weather brought heavy rainfall and ...,1252a030-a4cb-11ef-af46-346f24a52a12.wav,"[610, 37, 751, 397, 622, 101, 841, 66, 342, 32...","[610, 37, 474, 397, 191, 427, 266, 30, 248, 55..."
38,spencer-015,The vast expanse of the Grand Canyon revealed ...,7b7649f2-a4cb-11ef-a647-346f24a52a12.wav,"[612, 444, 587, 559, 540, 638, 725, 158, 323, ...","[303, 108, 296, 183, 142, 135, 321, 450, 105, ..."
39,spencer-015,Under close supervision from investors and aud...,df8dcda0-a4cb-11ef-8973-346f24a52a12.wav,"[538, 601, 11, 210, 292, 462, 385, 534, 489, 2...","[357, 727, 372, 410, 91, 289, 717, 551, 16, 14..."
40,vincent-001,"As morning sunbeams pierced the forest canopy,...",f9d56853-a4ca-11ef-a512-346f24a52a12.wav,"[924, 725, 619, 454, 363, 210, 619, 69, 624, 1...","[538, 725, 269, 4, 210, 210, 619, 69, 581, 145..."
41,vincent-001,"As negotiations concluded, key stakeholders ca...",a4b8969a-a4cb-11ef-97e6-346f24a52a12.wav,"[637, 725, 389, 619, 4, 210, 82, 243, 350, 587...","[551, 725, 269, 4, 210, 82, 243, 65, 619, 323,..."
42,vincent-001,"In contrast to yesterday's calmness, today's f...",3764995d-a4cb-11ef-8477-346f24a52a12.wav,"[551, 65, 210, 321, 315, 66, 389, 323, 11, 225...","[882, 416, 11, 66, 225, 605, 323, 727, 440, 36..."
43,vincent-001,Innovative software applications have transfor...,0c538ba3-a4cc-11ef-aa71-346f24a52a12.wav,"[815, 416, 440, 323, 362, 375, 66, 65, 434, 15...","[856, 416, 440, 323, 210, 375, 266, 158, 83, 1..."
44,vincent-001,"Meanwhile, across town, experts debated the im...",46e9dcc7-a4cc-11ef-a2f1-346f24a52a12.wav,"[808, 2, 350, 65, 37, 257, 30, 342, 713, 842, ...","[551, 2, 269, 199, 129, 275, 342, 611, 795, 84..."
45,vincent-001,"Oh, what a breathtaking sight the aurora borea...",5ed44eb9-a4cb-11ef-b82f-346f24a52a12.wav,"[147, 62, 180, 129, 342, 2, 254, 197, 337, 442...","[385, 62, 496, 728, 342, 307, 463, 744, 672, 5..."
46,vincent-001,The finance minister disclosed the budget cuts...,c26b2152-a4cb-11ef-88a3-346f24a52a12.wav,"[551, 37, 27, 567, 635, 53, 323, 440, 66, 587,...","[551, 129, 826, 920, 230, 7, 323, 440, 266, 31..."
47,vincent-001,The stormy weather brought heavy rainfall and ...,15a93607-a4cb-11ef-96dd-346f24a52a12.wav,"[118, 66, 280, 95, 837, 277, 561, 733, 453, 83...","[905, 37, 454, 622, 346, 273, 53, 323, 440, 26..."
48,vincent-001,The vast expanse of the Grand Canyon revealed ...,8213df7f-a4cb-11ef-95e9-346f24a52a12.wav,"[168, 126, 37, 192, 375, 389, 158, 323, 692, 4...","[815, 37, 471, 414, 167, 725, 389, 323, 53, 43..."
49,vincent-001,Under close supervision from investors and aud...,e0daf1d0-a4cb-11ef-9199-346f24a52a12.wav,"[494, 619, 11, 127, 62, 429, 651, 434, 8, 266,...","[551, 56, 210, 403, 37, 753, 640, 618, 820, 26..."

# Choosing CMOS speakers
## VCTK

In [3]:
%matplotlib inline
import pandas as pd
import random as rd
from IPython.display import Audio

rd.seed(42)

In [5]:
vctk_df = pd.read_csv('../data/VCTK-Corpus/test_metadata.csv')
vctk_df

,speaker_id,audio_id,text,whisper_transcription
0,p225,p225_016.wav,The Norsemen considered the rainbow as a bridg...,The Norsemen considered the rainbow as a brid...
1,p225,p225_022.wav,The actual primary rainbow observed is said to...,The actual primary rainbow observed is said t...
2,p225,p225_060.wav,Strathclyde police have appealed for witnesses.,Strathclyde police have appealed for witnesses.
3,p225,p225_062.wav,"I was very pleased with them today, though.",I was very pleased with them today though.
4,p225,p225_066.wav,It is a job creation scheme.,It is a job creation scheme.
...,...,...,...,...
4402,p376,p376_259.wav,It is not satisfied with the standard of fire ...,It is not satisfied with the standard of fire...
4403,p376,p376_263.wav,Similar measures are expected in England and W...,Similar measures are expected in England and ...
4404,p376,p376_272.wav,Its so awful.,It's so awful.
4405,p376,p376_284.wav,He was obviously very genuine.,He was obviously very genuine.
4406,p376,p376_285.wav,It is a vote of confidence in the skills in Sc...,It is a vote of confidence in the skills in S...

In [6]:
vcsk_speakers = pd.read_csv('../data/VCTK-Corpus/speaker_info.csv')
vcsk_speakers

      ID  AGE GENDER     ACCENTS            REGION
0    225   23      F     English  Southern England
1    226   22      M     English            Surrey
2    227   38      M     English           Cumbria
3    228   22      F     English  Southern England
4    229   23      F     English  Southern England
..   ...  ...    ...         ...               ...
103  362   29      F    American               NaN
104  363   22      M    Canadian           Toronto
105  364   23      M       Irish           Donegal
106  374   28      M  Australian           English
107  376   22      M      Indian               NaN

[108 rows x 5 columns]

In [7]:
vcsk_speakers = vcsk_speakers[vcsk_speakers['ID'].isin(vctk_df['speaker_id'].str.removeprefix('p').apply(int).unique())]
vcsk_speakers

      ID  AGE GENDER     ACCENTS            REGION
0    225   23      F     English  Southern England
1    226   22      M     English            Surrey
2    227   38      M     English           Cumbria
3    228   22      F     English  Southern England
4    229   23      F     English  Southern England
..   ...  ...    ...         ...               ...
103  362   29      F    American               NaN
104  363   22      M    Canadian           Toronto
105  364   23      M       Irish           Donegal
106  374   28      M  Australian           English
107  376   22      M      Indian               NaN

[107 rows x 5 columns]

In [8]:
vcsk_speakers_grouped = vcsk_speakers.groupby(['GENDER', 'ACCENTS'])['ID'].agg(list)
vcsk_speakers_grouped

GENDER  ACCENTS
F       American         [294, 297, 299, 300, 301, 305, 306, 308, 310, ...
        Canadian                                 [303, 307, 312, 317, 343]
        English          [225, 228, 229, 230, 231, 233, 236, 239, 240, ...
        Indian                                                       [248]
        Irish                               [266, 283, 288, 295, 313, 340]
        NewZealand                                                   [335]
        NorthernIrish                                 [238, 261, 293, 351]
        Scottish                                 [234, 249, 262, 264, 265]
        SouthAfrican                                       [314, 323, 336]
        Welsh                                                        [253]
M       American                                      [311, 334, 345, 360]
        Australian                                              [326, 374]
        Canadian                                           [302, 316, 363]
        English          [226, 227, 232, 243, 254, 256, 258, 259, 270, ...
        Indian                                                  [251, 376]
        Irish                                              [245, 298, 364]
        NorthernIrish                                           [292, 304]
        Scottish         [237, 241, 246, 247, 252, 255, 260, 263, 271, ...
        SouthAfrican                                                 [347]
Name: ID, dtype: object

In [9]:
rd.seed(42)
vcsk_speakers_chosen = vcsk_speakers_grouped.loc[(slice(None), ['American', 'English', 'Indian', 'Irish', 'Scottish'])].apply(rd.choice)
vcsk_speakers_chosen = vcsk_speakers_chosen.reset_index()
vcsk_speakers_chosen

  GENDER   ACCENTS   ID
0      F  American  300
1      F   English  225
2      F    Indian  248
3      F     Irish  283
4      F  Scottish  249
5      M  American  334
6      M   English  278
7      M    Indian  251
8      M     Irish  364
9      M  Scottish  281

In [10]:
vcsk_speakers_chosen['speaker_id'] = vcsk_speakers_chosen['ID'].apply(lambda x: f"p{x}")
vcsk_speakers_chosen

  GENDER   ACCENTS   ID speaker_id
0      F  American  300       p300
1      F   English  225       p225
2      F    Indian  248       p248
3      F     Irish  283       p283
4      F  Scottish  249       p249
5      M  American  334       p334
6      M   English  278       p278
7      M    Indian  251       p251
8      M     Irish  364       p364
9      M  Scottish  281       p281

In [11]:
rd.seed(42)
vcsk_wav_chosen = vctk_df.groupby('speaker_id')['audio_id'].agg(list).apply(lambda x: rd.sample(x, 4))
vcsk_wav_chosen = vcsk_wav_chosen.reset_index()
vcsk_wav_chosen

    speaker_id                                           audio_id
0         p225  [p225_351.wav, p225_062.wav, p225_016.wav, p22...
1         p226  [p226_153.wav, p226_150.wav, p226_116.wav, p22...
2         p227  [p227_384.wav, p227_081.wav, p227_392.wav, p22...
3         p228  [p228_024.wav, p228_014.wav, p228_063.wav, p22...
4         p229  [p229_139.wav, p229_318.wav, p229_012.wav, p22...
..         ...                                                ...
103       p362  [p362_033.wav, p362_258.wav, p362_106.wav, p36...
104       p363  [p363_258.wav, p363_198.wav, p363_188.wav, p36...
105       p364  [p364_083.wav, p364_002.wav, p364_202.wav, p36...
106       p374  [p374_275.wav, p374_245.wav, p374_198.wav, p37...
107       p376  [p376_259.wav, p376_068.wav, p376_106.wav, p37...

[108 rows x 2 columns]

In [12]:
vctk_cmos = pd.merge(vcsk_speakers_chosen, vcsk_wav_chosen, on='speaker_id')
vctk_cmos

,GENDER,ACCENTS,ID,speaker_id,audio_id
0,F,American,300,p300,"[p300_028.wav, p300_381.wav, p300_339.wav, p30..."
1,F,English,225,p225,"[p225_351.wav, p225_062.wav, p225_016.wav, p22..."
2,F,Indian,248,p248,"[p248_186.wav, p248_034.wav, p248_130.wav, p24..."
3,F,Irish,283,p283,"[p283_049.wav, p283_422.wav, p283_265.wav, p28..."
4,F,Scottish,249,p249,"[p249_223.wav, p249_276.wav, p249_211.wav, p24..."
5,M,American,334,p334,"[p334_030.wav, p334_018.wav, p334_260.wav, p33..."
6,M,English,278,p278,"[p278_050.wav, p278_404.wav, p278_017.wav, p27..."
7,M,Indian,251,p251,"[p251_140.wav, p251_345.wav, p251_282.wav, p25..."
8,M,Irish,364,p364,"[p364_083.wav, p364_002.wav, p364_202.wav, p36..."
9,M,Scottish,281,p281,"[p281_343.wav, p281_072.wav, p281_372.wav, p28..."

In [13]:
vctk_cmos = vctk_cmos.explode('audio_id').reset_index(drop=True)
vctk_cmos

   GENDER   ACCENTS   ID speaker_id      audio_id
0       F  American  300       p300  p300_028.wav
1       F  American  300       p300  p300_381.wav
2       F  American  300       p300  p300_339.wav
3       F  American  300       p300  p300_224.wav
4       F   English  225       p225  p225_351.wav
5       F   English  225       p225  p225_062.wav
6       F   English  225       p225  p225_016.wav
7       F   English  225       p225  p225_128.wav
8       F    Indian  248       p248  p248_186.wav
9       F    Indian  248       p248  p248_034.wav
10      F    Indian  248       p248  p248_130.wav
11      F    Indian  248       p248  p248_029.wav
12      F     Irish  283       p283  p283_049.wav
13      F     Irish  283       p283  p283_422.wav
14      F     Irish  283       p283  p283_265.wav
15      F     Irish  283       p283  p283_226.wav
16      F  Scottish  249       p249  p249_223.wav
17      F  Scottish  249       p249  p249_276.wav
18      F  Scottish  249       p249  p249_211.wav
19      F  Scottish  249       p249  p249_065.wav
20      M  American  334       p334  p334_030.wav
21      M  American  334       p334  p334_018.wav
22      M  American  334       p334  p334_260.wav
23      M  American  334       p334  p334_136.wav
24      M   English  278       p278  p278_050.wav
25      M   English  278       p278  p278_404.wav
26      M   English  278       p278  p278_017.wav
27      M   English  278       p278  p278_151.wav
28      M    Indian  251       p251  p251_140.wav
29      M    Indian  251       p251  p251_345.wav
30      M    Indian  251       p251  p251_282.wav
31      M    Indian  251       p251  p251_322.wav
32      M     Irish  364       p364  p364_083.wav
33      M     Irish  364       p364  p364_002.wav
34      M     Irish  364       p364  p364_202.wav
35      M     Irish  364       p364  p364_079.wav
36      M  Scottish  281       p281  p281_343.wav
37      M  Scottish  281       p281  p281_072.wav
38      M  Scottish  281       p281  p281_372.wav
39      M  Scottish  281       p281  p281_285.wav

In [14]:
vctk_cmos = pd.merge(vctk_cmos, vctk_df[['audio_id', 'text']], on='audio_id')
vctk_cmos

,GENDER,ACCENTS,ID,speaker_id,audio_id,text
0,F,American,300,p300,p300_028.wav,"The important thing was to be there, and to ex..."
1,F,American,300,p300,p300_381.wav,Who is going to pay their wages?
2,F,American,300,p300,p300_339.wav,But their bodies were found at lunchtime yeste...
3,F,American,300,p300,p300_224.wav,There is nothing like this back home.
4,F,English,225,p225,p225_351.wav,"After the match, do you ?"
5,F,English,225,p225,p225_062.wav,"I was very pleased with them today, though."
6,F,English,225,p225,p225_016.wav,The Norsemen considered the rainbow as a bridg...
7,F,English,225,p225,p225_128.wav,Mr Hall is believed to have a broken leg.
8,F,Indian,248,p248,p248_186.wav,They do not work for Glasgow City Council.
9,F,Indian,248,p248,p248_034.wav,Suggestions of the action being a punishment w...
10,F,Indian,248,p248,p248_130.wav,I had relied on him.
11,F,Indian,248,p248,p248_029.wav,The main concern is that it could interfere wi...
12,F,Irish,283,p283,p283_049.wav,No details of the talks were given.
13,F,Irish,283,p283,p283_422.wav,I am astonished at attack.
14,F,Irish,283,p283,p283_265.wav,"It depends on Labour, not on us."
15,F,Irish,283,p283,p283_226.wav,You could feel the heat.
16,F,Scottish,249,p249,p249_223.wav,It is perfectly evident that the time for an i...
17,F,Scottish,249,p249,p249_276.wav,"Yesterday, he had a chilling warning for the g..."
18,F,Scottish,249,p249,p249_211.wav,Ferguson should take note.
19,F,Scottish,249,p249,p249_065.wav,You did not change overnight.
20,M,American,334,p334,p334_030.wav,"Nothing is lost, everything is recycled."
21,M,American,334,p334,p334_018.wav,Aristotle thought that the rainbow was caused ...
22,M,American,334,p334,p334_260.wav,They would be wise to do just that.
23,M,American,334,p334,p334_136.wav,"By that time, however, it was already too late."
24,M,English,278,p278,p278_050.wav,I have learned from him.
25,M,English,278,p278,p278_404.wav,I had a fortunate war.
26,M,English,278,p278,p278_017.wav,Others have tried to explain the phenomenon ph...
27,M,English,278,p278,p278_151.wav,Nothing was meant by it.
28,M,Indian,251,p251,p251_140.wav,I am totally devoted to this job.
29,M,Indian,251,p251,p251_345.wav,You can see it on the training ground and arou...
30,M,Indian,251,p251,p251_282.wav,Thats the only thing I will say.
31,M,Indian,251,p251,p251_322.wav,We are now looking at the degrees of injury.
32,M,Irish,364,p364,p364_083.wav,His arrival could be the making of them.
33,M,Irish,364,p364,p364_002.wav,Ask her to bring these things with her from th...
34,M,Irish,364,p364,p364_202.wav,The attitude was good today.
35,M,Irish,364,p364,p364_079.wav,He wanted to talk to me about it.
36,M,Scottish,281,p281,p281_343.wav,"Last night, he pledged to clear his name."
37,M,Scottish,281,p281,p281_072.wav,"So is that it, then ?"
38,M,Scottish,281,p281,p281_372.wav,Its as wide as a church in here.
39,M,Scottish,281,p281,p281_285.wav,And they were being paid ?

In [15]:
vctk_cmos["dataset"] = "vctk"

In [16]:
vctk_cmos.to_csv('../data/VCTK-Corpus/vctk_cmos.csv', index=False)

## LJ

In [17]:
lj_df = pd.read_csv('../data/keithito_lj_speech/test_metadata.csv')
lj_df

,audio_id,text,speaker_id,whisper_transcription
0,LJ044-0001.wav,Report of the President's Commission on the As...,lg_speaker,Report of the President's Commission on the A...
1,LJ029-0001.wav,Report of the President's Commission on the As...,lg_speaker,Report of the President's Commission on the A...
2,LJ037-0001.wav,Report of the President's Commission on the As...,lg_speaker,Report of the President's Commission on the A...
3,LJ050-0197.wav,"According to Secretary Dillon,",lg_speaker,"According to Secretary Dillon,"
4,LJ043-0002.wav,The Warren Commission Report. By The President...,lg_speaker,the Warren Commission Report by the President...
...,...,...,...,...
2614,LJ013-0152.wav,at Montreuil. He was arraigned at the Old Bail...,lg_speaker,at Montreuil. He was arraigned at the Old Bai...
2615,LJ045-0052.wav,which Mrs. Paine had made in part to give her ...,lg_speaker,"which Mrs. Payne had made, in part, to give h..."
2616,LJ019-0382.wav,"As the years passed, great want of uniformity ...",lg_speaker,"As the years passed, great want of uniformity..."
2617,LJ007-0186.wav,"the undue authority given to prisoners, the le...",lg_speaker,"the undue authority given to prisoners, the l..."
2618,LJ036-0082.wav,Craig testified that later in the afternoon he...,lg_speaker,Craig testified that later in the afternoon h...

In [18]:
lj_df.groupby('text').count().sort_values('audio_id', ascending=False)

,audio_id,speaker_id,whisper_transcription
text,,,
And two other justices agreed with him.,2,2,2
Report of the President's Commission on the Assassination of President Kennedy. The Warren Commission Report. By The President's Commission on the Assassination of President Kennedy.,2,2,2
"The Commission believes, however,",2,2,2
"Within a month or two the bank of Messrs. Rogers and Co., Clement's Lane, was broken into.",1,1,1
"Within a year he was advanced to the post of chief clerk in the transfer department, at a salary of £150 a year.",1,1,1
...,...,...,...
Materials used to make bag.,1,1,1
Matters were on much the same footing at St. Albans.,1,1,1
May was smuggled in through a window on the esplanade behind an opened umbrella. When the place was quite deserted,1,1,1
McWatters also remembered that a man received a transfer at Lamar and Elm Streets and that a man in the lineup was about the size of this man.,1,1,1
Marina Oswald testified that the photographs were taken on a Sunday about 2 weeks before the attempted shooting of Maj. Gen. Edwin A. Walker,1,1,1

In [19]:
lj_samples_chosen = lj_df[lj_df['text'].apply(lambda x: x[0].isupper() and x[-1] == '.')].sample(4, random_state=42)
lj_samples_chosen

,audio_id,text,speaker_id,whisper_transcription
2007,LJ016-0139.wav,The last escape from Newgate was only three ye...,lg_speaker,The last escape from Newgate was only three y...
2176,LJ028-0499.wav,Ctesias mentions three hundred feet; probably ...,lg_speaker,Cessius mentions three hundred feet. Probably...
1571,LJ009-0233.wav,"The rope still broke sometimes, although it wa...",lg_speaker,"The rope still broke sometimes, although it w..."
1097,LJ016-0402.wav,"No woman could resist him, he calmly assured M...",lg_speaker,"No woman could resist him, he calmly assured ..."

In [20]:
lj_cmos = pd.DataFrame({
    'GENDER': ['F']*4,
    'ACCENTS': [None]*4,
    "ID": ['lj']*4,
    "speaker_id": ['lj_speaker']*4,
    "audio_id": lj_samples_chosen["audio_id"].tolist(),
    "text": lj_samples_chosen["text"].tolist(),
    "dataset": ["lj_speech"]*4
})
lj_cmos

,GENDER,ACCENTS,ID,speaker_id,audio_id,text,dataset
0,F,None,lj,lj_speaker,LJ016-0139.wav,The last escape from Newgate was only three ye...,lj_speech
1,F,None,lj,lj_speaker,LJ028-0499.wav,Ctesias mentions three hundred feet; probably ...,lj_speech
2,F,None,lj,lj_speaker,LJ009-0233.wav,"The rope still broke sometimes, although it wa...",lj_speech
3,F,None,lj,lj_speaker,LJ016-0402.wav,"No woman could resist him, he calmly assured M...",lj_speech

In [21]:
lj_cmos.to_csv('../data/keithito_lj_speech/lj_cmos.csv', index=False)

In [22]:
cmos_df = pd.concat([vctk_cmos, lj_cmos])
cmos_df

,GENDER,ACCENTS,ID,speaker_id,audio_id,text,dataset
0,F,American,300,p300,p300_028.wav,"The important thing was to be there, and to ex...",vctk
1,F,American,300,p300,p300_381.wav,Who is going to pay their wages?,vctk
2,F,American,300,p300,p300_339.wav,But their bodies were found at lunchtime yeste...,vctk
3,F,American,300,p300,p300_224.wav,There is nothing like this back home.,vctk
4,F,English,225,p225,p225_351.wav,"After the match, do you ?",vctk
5,F,English,225,p225,p225_062.wav,"I was very pleased with them today, though.",vctk
6,F,English,225,p225,p225_016.wav,The Norsemen considered the rainbow as a bridg...,vctk
7,F,English,225,p225,p225_128.wav,Mr Hall is believed to have a broken leg.,vctk
8,F,Indian,248,p248,p248_186.wav,They do not work for Glasgow City Council.,vctk
9,F,Indian,248,p248,p248_034.wav,Suggestions of the action being a punishment w...,vctk
10,F,Indian,248,p248,p248_130.wav,I had relied on him.,vctk
11,F,Indian,248,p248,p248_029.wav,The main concern is that it could interfere wi...,vctk
12,F,Irish,283,p283,p283_049.wav,No details of the talks were given.,vctk
13,F,Irish,283,p283,p283_422.wav,I am astonished at attack.,vctk
14,F,Irish,283,p283,p283_265.wav,"It depends on Labour, not on us.",vctk
15,F,Irish,283,p283,p283_226.wav,You could feel the heat.,vctk
16,F,Scottish,249,p249,p249_223.wav,It is perfectly evident that the time for an i...,vctk
17,F,Scottish,249,p249,p249_276.wav,"Yesterday, he had a chilling warning for the g...",vctk
18,F,Scottish,249,p249,p249_211.wav,Ferguson should take note.,vctk
19,F,Scottish,249,p249,p249_065.wav,You did not change overnight.,vctk
20,M,American,334,p334,p334_030.wav,"Nothing is lost, everything is recycled.",vctk
21,M,American,334,p334,p334_018.wav,Aristotle thought that the rainbow was caused ...,vctk
22,M,American,334,p334,p334_260.wav,They would be wise to do just that.,vctk
23,M,American,334,p334,p334_136.wav,"By that time, however, it was already too late.",vctk
24,M,English,278,p278,p278_050.wav,I have learned from him.,vctk
25,M,English,278,p278,p278_404.wav,I had a fortunate war.,vctk
26,M,English,278,p278,p278_017.wav,Others have tried to explain the phenomenon ph...,vctk
27,M,English,278,p278,p278_151.wav,Nothing was meant by it.,vctk
28,M,Indian,251,p251,p251_140.wav,I am totally devoted to this job.,vctk
29,M,Indian,251,p251,p251_345.wav,You can see it on the training ground and arou...,vctk
30,M,Indian,251,p251,p251_282.wav,Thats the only thing I will say.,vctk
31,M,Indian,251,p251,p251_322.wav,We are now looking at the degrees of injury.,vctk
32,M,Irish,364,p364,p364_083.wav,His arrival could be the making of them.,vctk
33,M,Irish,364,p364,p364_002.wav,Ask her to bring these things with her from th...,vctk
34,M,Irish,364,p364,p364_202.wav,The attitude was good today.,vctk
35,M,Irish,364,p364,p364_079.wav,He wanted to talk to me about it.,vctk
36,M,Scottish,281,p281,p281_343.wav,"Last night, he pledged to clear his name.",vctk
37,M,Scottish,281,p281,p281_072.wav,"So is that it, then ?",vctk
38,M,Scottish,281,p281,p281_372.wav,Its as wide as a church in here.,vctk
39,M,Scottish,281,p281,p281_285.wav,And they were being paid ?,vctk
0,F,None,lj,lj_speaker,LJ016-0139.wav,The last escape from Newgate was only three ye...,lj_speech
1,F,None,lj,lj_speaker,LJ028-0499.wav,Ctesias mentions three hundred feet; probably ...,lj_speech
2,F,None,lj,lj_speaker,LJ009-0233.wav,"The rope still broke sometimes, although it wa...",lj_speech
3,F,None,lj,lj_speaker,LJ016-0402.wav,"No woman could resist him, he calmly assured M...",lj_speech

In [23]:
cmos_df.to_csv('../data/cmos_speakers.csv', index=False)

# Calibration samples

In [24]:
cmos_df = pd.read_csv('../data/cmos_speakers.csv')
cmos_df

,GENDER,ACCENTS,ID,speaker_id,audio_id,text,dataset
0,F,American,300,p300,p300_028.wav,"The important thing was to be there, and to ex...",vctk
1,F,American,300,p300,p300_381.wav,Who is going to pay their wages?,vctk
2,F,American,300,p300,p300_339.wav,But their bodies were found at lunchtime yeste...,vctk
3,F,American,300,p300,p300_224.wav,There is nothing like this back home.,vctk
4,F,English,225,p225,p225_351.wav,"After the match, do you ?",vctk
5,F,English,225,p225,p225_062.wav,"I was very pleased with them today, though.",vctk
6,F,English,225,p225,p225_016.wav,The Norsemen considered the rainbow as a bridg...,vctk
7,F,English,225,p225,p225_128.wav,Mr Hall is believed to have a broken leg.,vctk
8,F,Indian,248,p248,p248_186.wav,They do not work for Glasgow City Council.,vctk
9,F,Indian,248,p248,p248_034.wav,Suggestions of the action being a punishment w...,vctk
10,F,Indian,248,p248,p248_130.wav,I had relied on him.,vctk
11,F,Indian,248,p248,p248_029.wav,The main concern is that it could interfere wi...,vctk
12,F,Irish,283,p283,p283_049.wav,No details of the talks were given.,vctk
13,F,Irish,283,p283,p283_422.wav,I am astonished at attack.,vctk
14,F,Irish,283,p283,p283_265.wav,"It depends on Labour, not on us.",vctk
15,F,Irish,283,p283,p283_226.wav,You could feel the heat.,vctk
16,F,Scottish,249,p249,p249_223.wav,It is perfectly evident that the time for an i...,vctk
17,F,Scottish,249,p249,p249_276.wav,"Yesterday, he had a chilling warning for the g...",vctk
18,F,Scottish,249,p249,p249_211.wav,Ferguson should take note.,vctk
19,F,Scottish,249,p249,p249_065.wav,You did not change overnight.,vctk
20,M,American,334,p334,p334_030.wav,"Nothing is lost, everything is recycled.",vctk
21,M,American,334,p334,p334_018.wav,Aristotle thought that the rainbow was caused ...,vctk
22,M,American,334,p334,p334_260.wav,They would be wise to do just that.,vctk
23,M,American,334,p334,p334_136.wav,"By that time, however, it was already too late.",vctk
24,M,English,278,p278,p278_050.wav,I have learned from him.,vctk
25,M,English,278,p278,p278_404.wav,I had a fortunate war.,vctk
26,M,English,278,p278,p278_017.wav,Others have tried to explain the phenomenon ph...,vctk
27,M,English,278,p278,p278_151.wav,Nothing was meant by it.,vctk
28,M,Indian,251,p251,p251_140.wav,I am totally devoted to this job.,vctk
29,M,Indian,251,p251,p251_345.wav,You can see it on the training ground and arou...,vctk
30,M,Indian,251,p251,p251_282.wav,Thats the only thing I will say.,vctk
31,M,Indian,251,p251,p251_322.wav,We are now looking at the degrees of injury.,vctk
32,M,Irish,364,p364,p364_083.wav,His arrival could be the making of them.,vctk
33,M,Irish,364,p364,p364_002.wav,Ask her to bring these things with her from th...,vctk
34,M,Irish,364,p364,p364_202.wav,The attitude was good today.,vctk
35,M,Irish,364,p364,p364_079.wav,He wanted to talk to me about it.,vctk
36,M,Scottish,281,p281,p281_343.wav,"Last night, he pledged to clear his name.",vctk
37,M,Scottish,281,p281,p281_072.wav,"So is that it, then ?",vctk
38,M,Scottish,281,p281,p281_372.wav,Its as wide as a church in here.,vctk
39,M,Scottish,281,p281,p281_285.wav,And they were being paid ?,vctk
40,F,NaN,lj,lj_speaker,LJ016-0139.wav,The last escape from Newgate was only three ye...,lj_speech
41,F,NaN,lj,lj_speaker,LJ028-0499.wav,Ctesias mentions three hundred feet; probably ...,lj_speech
42,F,NaN,lj,lj_speaker,LJ009-0233.wav,"The rope still broke sometimes, although it wa...",lj_speech
43,F,NaN,lj,lj_speaker,LJ016-0402.wav,"No woman could resist him, he calmly assured M...",lj_speech

In [25]:
vctk_df_filtered = vctk_df[~vctk_df['audio_id'].isin(cmos_df['audio_id'])]
vctk_df_filtered

,speaker_id,audio_id,text,whisper_transcription
1,p225,p225_022.wav,The actual primary rainbow observed is said to...,The actual primary rainbow observed is said t...
2,p225,p225_060.wav,Strathclyde police have appealed for witnesses.,Strathclyde police have appealed for witnesses.
4,p225,p225_066.wav,It is a job creation scheme.,It is a job creation scheme.
5,p225,p225_072.wav,"What kind of man does that, Mr Dick ?","What kind of man does that, Mr. Dick?"
6,p225,p225_084.wav,"He is delighted, and he has every right to be.",He is delighted and he has every right to be.
...,...,...,...,...
4402,p376,p376_259.wav,It is not satisfied with the standard of fire ...,It is not satisfied with the standard of fire...
4403,p376,p376_263.wav,Similar measures are expected in England and W...,Similar measures are expected in England and ...
4404,p376,p376_272.wav,Its so awful.,It's so awful.
4405,p376,p376_284.wav,He was obviously very genuine.,He was obviously very genuine.
4406,p376,p376_285.wav,It is a vote of confidence in the skills in Sc...,It is a vote of confidence in the skills in S...

In [28]:
rd.seed(42)
vcsk_wav_chosen_calib = vctk_df_filtered.groupby('speaker_id')['audio_id'].agg(list).apply(lambda x: rd.choice(x))
vcsk_wav_chosen_calib = vcsk_wav_chosen_calib.reset_index()
vcsk_wav_chosen_calib

    speaker_id      audio_id
0         p225  p225_072.wav
1         p226  p226_009.wav
2         p227  p227_194.wav
3         p228  p228_167.wav
4         p229  p229_139.wav
..         ...           ...
103       p362  p362_075.wav
104       p363  p363_115.wav
105       p364  p364_292.wav
106       p374  p374_372.wav
107       p376  p376_225.wav

[108 rows x 2 columns]

In [30]:
vctk_cmos_calib = pd.merge(vcsk_speakers_chosen, vcsk_wav_chosen_calib, on='speaker_id')
vctk_cmos_calib

  GENDER   ACCENTS   ID speaker_id      audio_id
0      F  American  300       p300  p300_263.wav
1      F   English  225       p225  p225_072.wav
2      F    Indian  248       p248  p248_139.wav
3      F     Irish  283       p283  p283_459.wav
4      F  Scottish  249       p249  p249_174.wav
5      M  American  334       p334  p334_253.wav
6      M   English  278       p278  p278_310.wav
7      M    Indian  251       p251  p251_190.wav
8      M     Irish  364       p364  p364_292.wav
9      M  Scottish  281       p281  p281_035.wav

In [34]:
vctk_cmos_calib = pd.merge(vctk_cmos_calib, vctk_df[['audio_id', 'text']], on='audio_id')
vctk_cmos_calib

,GENDER,ACCENTS,ID,speaker_id,audio_id,text
0,F,American,300,p300,p300_263.wav,That means no more taxation by stealth.
1,F,English,225,p225,p225_072.wav,"What kind of man does that, Mr Dick ?"
2,F,Indian,248,p248,p248_139.wav,It was typical.
3,F,Irish,283,p283,p283_459.wav,He was confronted by police.
4,F,Scottish,249,p249,p249_174.wav,We have a budget in March.
5,M,American,334,p334,p334_253.wav,Im getting back up there now.
6,M,English,278,p278,p278_310.wav,I couldnt really work outside Edinburgh.
7,M,Indian,251,p251,p251_190.wav,"However, this idea is never developed."
8,M,Irish,364,p364,p364_292.wav,I was the willing journeyman.
9,M,Scottish,281,p281,p281_035.wav,She failed in her action.

In [31]:
lj_df_calib = lj_df[~lj_df['audio_id'].isin(cmos_df['audio_id'])]
lj_df_calib

,audio_id,text,speaker_id,whisper_transcription
0,LJ044-0001.wav,Report of the President's Commission on the As...,lg_speaker,Report of the President's Commission on the A...
1,LJ029-0001.wav,Report of the President's Commission on the As...,lg_speaker,Report of the President's Commission on the A...
2,LJ037-0001.wav,Report of the President's Commission on the As...,lg_speaker,Report of the President's Commission on the A...
3,LJ050-0197.wav,"According to Secretary Dillon,",lg_speaker,"According to Secretary Dillon,"
4,LJ043-0002.wav,The Warren Commission Report. By The President...,lg_speaker,the Warren Commission Report by the President...
...,...,...,...,...
2614,LJ013-0152.wav,at Montreuil. He was arraigned at the Old Bail...,lg_speaker,at Montreuil. He was arraigned at the Old Bai...
2615,LJ045-0052.wav,which Mrs. Paine had made in part to give her ...,lg_speaker,"which Mrs. Payne had made, in part, to give h..."
2616,LJ019-0382.wav,"As the years passed, great want of uniformity ...",lg_speaker,"As the years passed, great want of uniformity..."
2617,LJ007-0186.wav,"the undue authority given to prisoners, the le...",lg_speaker,"the undue authority given to prisoners, the l..."
2618,LJ036-0082.wav,Craig testified that later in the afternoon he...,lg_speaker,Craig testified that later in the afternoon h...

In [32]:
lj_df_calib.sample(1, random_state=42)

,audio_id,text,speaker_id,whisper_transcription
2602,LJ003-0305.wav,The provision of more baths was also suggested...,lg_speaker,The provision of more baths was also suggeste...

In [41]:
cmos_calib_df = pd.concat([vctk_cmos_calib[['speaker_id', 'audio_id', 'text']], lj_df_calib.sample(1, random_state=42)[['speaker_id', 'audio_id', 'text']]])
cmos_calib_df

,speaker_id,audio_id,text
0,p300,p300_263.wav,That means no more taxation by stealth.
1,p225,p225_072.wav,"What kind of man does that, Mr Dick ?"
2,p248,p248_139.wav,It was typical.
3,p283,p283_459.wav,He was confronted by police.
4,p249,p249_174.wav,We have a budget in March.
5,p334,p334_253.wav,Im getting back up there now.
6,p278,p278_310.wav,I couldnt really work outside Edinburgh.
7,p251,p251_190.wav,"However, this idea is never developed."
8,p364,p364_292.wav,I was the willing journeyman.
9,p281,p281_035.wav,She failed in her action.
2602,lg_speaker,LJ003-0305.wav,The provision of more baths was also suggested...

In [42]:
cmos_calib_df.loc[cmos_calib_df['speaker_id'] == 'lg_speaker', 'speaker_id'] = 'lj_speaker'
cmos_calib_df

,speaker_id,audio_id,text
0,p300,p300_263.wav,That means no more taxation by stealth.
1,p225,p225_072.wav,"What kind of man does that, Mr Dick ?"
2,p248,p248_139.wav,It was typical.
3,p283,p283_459.wav,He was confronted by police.
4,p249,p249_174.wav,We have a budget in March.
5,p334,p334_253.wav,Im getting back up there now.
6,p278,p278_310.wav,I couldnt really work outside Edinburgh.
7,p251,p251_190.wav,"However, this idea is never developed."
8,p364,p364_292.wav,I was the willing journeyman.
9,p281,p281_035.wav,She failed in her action.
2602,lj_speaker,LJ003-0305.wav,The provision of more baths was also suggested...

In [43]:
cmos_calib_df.to_csv('../data/cmos_calib_samples.csv', index=False)